// Generate comprehensive parts master dictionary
// Output: parts_master.json (EN → {zh, sw})
const fs = require('fs');

const dict = {};

function add(en, zh, sw) {
  if (!en || dict[en]) return;
  dict[en] = { zh: zh || '', sw: sw || '' };
}

// ═══════════════════════════════════════════════════════════
// ENGINE — 发动机 — INJINI
// ═══════════════════════════════════════════════════════════
add('ENGINE', '发动机', 'injini');
add('ENGINE ASSEMBLY', '发动机总成', 'injini kamili');
add('ENGINE BLOCK', '缸体', 'bloki ya injini');
add('ENGINE GASKET', '发动机垫片', 'gasketi ya injini');
add('ENGINE GASKET SET', '发动机大修包', 'seti ya gasketi');
add('ENGINE GASKET KIT', '发动机密封垫套装', 'seti ya gasketi ya injini');
add('ENGINE MOUNTING', '发动机支架', 'mounti ya injini');
add('ENGINE MOUNT', '发动机支架', 'mounti ya injini');
add('ENGINE BUSH', '发动机胶套', 'bushi ya injini');
add('ENGINE OVERHAUL KIT', '发动机大修包', 'seti ya overhaul');
add('ENGINE VALVE', '发动机气门', 'valvu ya injini');
add('ENGINE OIL', '机油', 'mafuta ya injini');
add('ENGINE OIL 0W-20', '机油0W-20', 'mafuta ya injini 0W-20');
add('ENGINE OIL 5W-20', '机油5W-20', 'mafuta ya injini 5W-20');
add('ENGINE OIL 5W-30', '机油5W-30', 'mafuta ya injini 5W-30');
add('ENGINE OIL 5W-30 GOLDEN', '金色机油5W-30', 'mafuta ya injini 5W-30 dhahabu');
add('ENGINE OIL 5W-30 1 LITRE', '机油5W-30 1升', 'mafuta ya injini 5W-30 lita 1');
add('ENGINE OIL 5W-30 4 LITRES', '机油5W-30 4升', 'mafuta ya injini 5W-30 lita 4');
add('ENGINE OIL 5W-30 5 LITRES', '机油5W-30 5升', 'mafuta ya injini 5W-30 lita 5');
add('ENGINE OIL 5W-40', '机油5W-40', 'mafuta ya injini 5W-40');
add('ENGINE OIL 10W-30', '机油10W-30', 'mafuta ya injini 10W-30');
add('ENGINE OIL 10W-40', '机油10W-40', 'mafuta ya injini 10W-40');
add('ENGINE OIL 15W-40', '机油15W-40', 'mafuta ya injini 15W-40');
add('ENGINE OIL 15W-40 BLACK', '黑色机油15W-40', 'mafuta ya injini 15W-40 nyeusi');
add('ENGINE OIL 15W-40 1 LITRE', '机油15W-40 1升', 'mafuta ya injini 15W-40 lita 1');
add('ENGINE OIL 15W-40 2 LITRES', '机油15W-40 2升', 'mafuta ya injini 15W-40 lita 2');
add('ENGINE OIL 15W-40 5 LITRES', '机油15W-40 5升', 'mafuta ya injini 15W-40 lita 5');
add('ENGINE OIL 15W-40 8 LITRES', '机油15W-40 8升', 'mafuta ya injini 15W-40 lita 8');
add('ENGINE OIL 20W-50', '机油20W-50', 'mafuta ya injini 20W-50');
add('SEMI SYNTHETIC OIL', '半合成机油', 'mafuta ya nusu synthetic');
add('FULLY SYNTHETIC OIL', '全合成机油', 'mafuta ya synthetic kamili');
add('MINERAL OIL', '矿物机油', 'mafuta ya madini');
add('MOTOR OIL', '发动机机油', 'mafuta ya mota');
add('ENGINE LUBRICANT', '发动机润滑油', 'mafuta ya kulainisha injini');
add('OIL ADDITIVE', '机油添加剂', 'kiongezi cha mafuta');
add('OIL CHANGE', '更换机油', 'kubadilisha mafuta');
add('OIL SERVICE', '机油保养', 'service ya mafuta');
add('OIL FLUSH', '机油清洗', 'kusafisha mafuta');
add('ENGINE OIL LEAK', '发动机漏油', 'kuvuja mafuta ya injini');
add('ENGINE FLUSH', '发动机清洗', 'kusafisha injini');
add('ENGINE TUNE-UP', '发动机调校', 'kutengeneza injini');
add('ENGINE DIAGNOSIS', '发动机诊断', 'uchunguzi wa injini');
add('ENGINE SCANNING', '发动机电脑检测', 'kuchanganua injini');
add('ENGINE OVERHAUL', '发动机大修', 'overhaul ya injini');
add('ENGINE REBUILD', '发动机翻新', 'kujenga upya injini');
add('ENGINE REPAIR', '发动机维修', 'kutengeneza injini');
add('ENGINE SWAP', '更换发动机', 'kubadilisha injini');
add('ENGINE TIMING', '发动机正时', 'timing ya injini');
add('ENGINE KNOCK', '发动机爆震', 'injini kugonga');
add('ENGINE OVERHEATING', '发动机过热', 'injini kupata joto');
add('ENGINE MISFIRE', '发动机缺火', 'injini kukosa moto');
add('ENGINE VIBRATION', '发动机抖动', 'injini kutetemeka');
add('ENGINE NOISE', '发动机异响', 'injini kelele');

// Cylinder Head / Valvetrain
add('CYLINDER HEAD', '缸盖', 'kichwa cha silinda');
add('CYLINDER HEAD GASKET', '缸垫', 'gasketi ya kichwa cha silinda');
add('HEAD GASKET', '缸垫', 'gasketi ya kichwa');
add('CYLINDER HEAD BOLT', '缸盖螺丝', 'bolti ya kichwa cha silinda');
add('CYLINDER HEAD COVER', '气门室盖', 'kifuniko cha kichwa cha silinda');
add('CYLINDER HEAD COVER GASKET', '气门室盖垫', 'gasketi ya kifuniko cha kichwa');
add('ROCKER COVER', '气门室盖', 'kifuniko cha roka');
add('ROCKER COVER GASKET', '气门室盖垫片', 'gasketi ya kifuniko cha roka');
add('ROCKER ARM', '摇臂', 'roka');
add('ROCKER ARM SHAFT', '摇臂轴', 'shafti ya roka');
add('CYLINDER LINER', '缸套', 'mjengo wa silinda');
add('CYLINDER BLOCK', '缸体', 'bloki ya silinda');
add('CYLINDER BORE', '缸径', 'kimo cha silinda');
add('VALVE', '气门', 'valvu');
add('INTAKE VALVE', '进气门', 'valvu ya kuingiza');
add('EXHAUST VALVE', '排气门', 'valvu ya kutolea');
add('VALVE SEAT', '气门座', 'kiti cha valvu');
add('VALVE GUIDE', '气门导管', 'mwongozo wa valvu');
add('VALVE SEAL', '气门油封', 'seal ya valvu');
add('VALVE STEM SEAL', '气门杆油封', 'seal ya kijiti cha valvu');
add('VALVE SPRING', '气门弹簧', 'springi ya valvu');
add('VALVE COTTER', '气门锁片', 'cotter ya valvu');
add('VALVE KEEPER', '气门锁片', 'kishikiza valvu');
add('VALVE LIFTER', '气门挺杆', 'lifti ya valvu');
add('VALVE TAPPET', '气门挺柱', 'tappet ya valvu');
add('VALVE PUSH ROD', '气门推杆', 'push rod ya valvu');
add('VALVE ROCKER', '气门摇臂', 'roka ya valvu');
add('VALVE SPRING RETAINER', '气门弹簧座', 'retainer ya springi');
add('VALVE TIMING', '气门正时', 'timing ya valvu');
add('VALVE ADJUSTMENT', '气门间隙调整', 'kurekebisha valvu');
add('VALVE CLEARANCE', '气门间隙', 'nafasi ya valvu');
add('VALVE GRINDING', '气门研磨', 'kusaga valvu');
add('VALVE LAPPING', '气门研磨', 'kulapa valvu');
add('HYDRAULIC LIFTER', '液压挺柱', 'lifti ya hydraulic');
add('SOLID LIFTER', '固定挺柱', 'lifti ngumu');
add('MULTIVALVE ENGINE', '多气门发动机', 'injini ya valvu nyingi');
add('OVERHEAD VALVE', '顶置气门', 'valvu ya juu');
add('OVERHEAD CAMSHAFT', '顶置凸轮轴', 'camshafti ya juu');
add('VARIABLE VALVE TIMING', '可变气门正时', 'timing ya valvu inayobadilika');
add('VVT-I', '智能可变气门正时', 'VVT-i');
add('VVTI', '可变气门正时', 'VVT');
add('VTEC', '可变气门正时及升程', 'VTEC');
add('VANOS', '可变凸轮轴正时', 'VANOS');

// CAMSHAFT / CRANKSHAFT
add('CAMSHAFT', '凸轮轴', 'camshafti');
add('CAMSHAFT SENSOR', '凸轮轴传感器', 'sensa ya camshafti');
add('CAMSHAFT POSITION SENSOR', '凸轮轴位置传感器', 'sensa ya nafasi ya camshafti');
add('CAMSHAFT PULLEY', '凸轮轴皮带轮', 'pulley ya camshafti');
add('CAMSHAFT SPROCKET', '凸轮轴链轮', 'sproketi ya camshafti');
add('CAMSHAFT SEAL', '凸轮轴油封', 'seal ya camshafti');
add('CAMSHAFT BEARING', '凸轮轴轴承', 'bearing ya camshafti');
add('CAMSHAFT CAP', '凸轮轴盖', 'kifuniko cha camshafti');
add('CAMSHAFT LOBE', '凸轮轴凸角', 'lobe ya camshafti');
add('CAMSHAFT CHAIN', '凸轮轴链条', 'cheni ya camshafti');
add('CAMSHAFT GEAR', '凸轮轴齿轮', 'giya ya camshafti');
add('CRANKSHAFT', '曲轴', 'crankshafti');
add('CRANKSHAFT SENSOR', '曲轴传感器', 'sensa ya crankshafti');
add('CRANKSHAFT POSITION SENSOR', '曲轴位置传感器', 'sensa ya nafasi ya crankshafti');
add('CRANKSHAFT PULLEY', '曲轴皮带轮', 'pulley ya crankshafti');
add('CRANKSHAFT BEARING', '曲轴瓦', 'bearing ya crankshafti');
add('CRANKSHAFT MAIN BEARING', '曲轴主轴瓦', 'bearing kuu ya crankshafti');
add('CRANKSHAFT JOURNAL', '曲轴轴颈', 'journal ya crankshafti');
add('CRANKSHAFT SEAL', '曲轴油封', 'seal ya crankshafti');
add('CRANKSHAFT FRONT SEAL', '曲轴前油封', 'seal ya mbele ya crankshafti');
add('CRANKSHAFT REAR SEAL', '曲轴后油封', 'seal ya nyuma ya crankshafti');
add('CRANKSHAFT THROW', '曲轴曲柄', 'throw ya crankshafti');
add('CRANKSHAFT SPROCKET', '曲轴链轮', 'sproketi ya crankshafti');
add('CRANKSHAFT PULLEY BOLT', '曲轴皮带轮螺丝', 'bolti ya pulley ya crankshafti');
add('CRANKSHAFT DAMPER', '曲轴减震器', 'damper ya crankshafti');
add('CRANKSHAFT BALANCER', '曲轴平衡器', 'balancer ya crankshafti');
add('CRANKSHAFT KEY', '曲轴键', 'ufunguo wa crankshafti');

// PISTON / CONNECTING ROD
add('PISTON', '活塞', 'pistoni');
add('PISTON ASSEMBLY', '活塞总成', 'pistoni kamili');
add('PISTON RING', '活塞环', 'pete ya pistoni');
add('PISTON RING SET', '活塞环组', 'seti ya pete za pistoni');
add('PISTON RING COMPRESSOR', '活塞环压缩器', 'compressor ya pete');
add('PISTON PIN', '活塞销', 'pini ya pistoni');
add('PISTON LINER', '活塞套', 'mjengo wa pistoni');
add('PISTON COOLING JET', '活塞冷却喷嘴', 'jeti ya kupoza pistoni');
add('PISTON SLAP', '活塞敲缸', 'pistoni kugonga');
add('CONNECTING ROD', '连杆', 'fimbo ya kuunganisha');
add('CONNECTING ROD BEARING', '连杆瓦', 'bearing ya connecting rod');
add('CONNECTING ROD BOLT', '连杆螺丝', 'bolti ya connecting rod');
add('CONNECTING ROD BUSH', '连杆套', 'bushi ya connecting rod');
add('THRUST WASHER', '止推垫圈', 'washer ya kusukuma');
add('WRIST PIN', '活塞销', 'pini ya kifundo');

// TIMING
add('TIMING BELT', '正时皮带', 'mkanda wa timing');
add('TIMING BELT KIT', '正时皮带套装', 'seti ya mkanda wa timing');
add('TIMING BELT TENSIONER', '正时皮带涨紧轮', 'tensioner ya mkanda wa timing');
add('TIMING BELT PULLEY', '正时皮带轮', 'pulley ya mkanda wa timing');
add('TIMING BELT COVER', '正时皮带罩', 'kifuniko cha mkanda wa timing');
add('TIMING CHAIN', '正时链条', 'cheni ya timing');
add('TIMING CHAIN KIT', '正时链条套装', 'seti ya cheni ya timing');
add('TIMING CHAIN TENSIONER', '正时链条涨紧器', 'tensioner ya cheni ya timing');
add('TIMING CHAIN GUIDE', '正时链条导轨', 'mwongozo wa cheni ya timing');
add('TIMING CHAIN COVER', '正时链条盖', 'kifuniko cha cheni ya timing');
add('TIMING CHAIN COVER GASKET', '正时盖垫片', 'gasketi ya kifuniko cha cheni');
add('TIMING COVER GASKET', '正时盖垫片', 'gasketi ya kifuniko cha timing');
add('TIMING GEAR', '正时齿轮', 'giya ya timing');
add('TIMING KIT', '正时套装', 'seti ya timing');
add('TIMING MARK', '正时标记', 'alama ya timing');
add('TIMING BELT REPLACEMENT', '更换正时皮带', 'kubadilisha mkanda wa timing');

// TENSIONER / IDLER / PULLEY
add('TENSIONER', '涨紧轮', 'tensioner');
add('TENSIONER PULLEY', '涨紧轮', 'pulley ya tensioner');
add('TENSIONER BELT', '皮带涨紧器', 'tensioner ya mkanda');
add('TENSIONER SPRING', '涨紧弹簧', 'springi ya tensioner');
add('IDLER PULLEY', '惰轮', 'pulley ya uvivu');
add('IDLER ARM', '惰轮臂', 'arm ya uvivu');
add('IDLER GEAR', '惰齿轮', 'giya ya uvivu');
add('PULLEY', '皮带轮', 'pulley');
add('CRANKSHAFT PULLEY', '曲轴皮带轮', 'pulley ya crankshafti');
add('ALTERNATOR PULLEY', '发电机皮带轮', 'pulley ya alterneta');
add('POWER STEERING PUMP PULLEY', '助力泵皮带轮', 'pulley ya pampu ya usukani');
add('AC PULLEY', '空调皮带轮', 'pulley ya AC');
add('WATER PUMP PULLEY', '水泵皮带轮', 'pulley ya pampu ya maji');
add('FAN PULLEY', '风扇皮带轮', 'pulley ya feni');
add('UNDERDRIVE PULLEY', '减速皮带轮', 'pulley ya kupunguza');
add('OVERDRIVE PULLEY', '加速皮带轮', 'pulley ya kuongeza');
add('PULLEY KIT', '皮带轮套装', 'seti ya pulley');
add('SERPENTINE BELT', '多楔带', 'mkanda wa nyoka');
add('SERPENTINE BELT TENSIONER', '多楔带涨紧器', 'tensioner ya mkanda wa nyoka');
add('V-BELT', '三角皮带', 'mkanda V');
add('FAN BELT', '风扇皮带', 'mkanda wa feni');
add('ALTERNATOR BELT', '发电机皮带', 'mkanda wa alterneta');
add('AC BELT', '空调皮带', 'mkanda wa AC');
add('POWER STEERING BELT', '助力泵皮带', 'mkanda wa usukani');
add('DRIVE BELT', '驱动皮带', 'mkanda wa kusukuma');
add('MAIN DRIVE BELT', '主驱动皮带', 'mkanda mkuu wa kusukuma');
add('ACCESSORY BELT', '附件皮带', 'mkanda wa vifaa');
add('RIBBED BELT', '多楔带', 'mkanda wa mbavu');
add('FLAT BELT', '平皮带', 'mkanda gorofa');
add('COGGED BELT', '齿形皮带', 'mkanda wa meno');
add('BELT DRESSING', '皮带养护剂', 'dawa ya mkanda');
add('BELT SQUEAL', '皮带异响', 'mkanda kulia');
add('BELT SLIP', '皮带打滑', 'mkanda kuteleza');
add('BELT TENSION', '皮带张力', 'mvutano wa mkanda');
add('BELT REPLACEMENT', '更换皮带', 'kubadilisha mkanda');

// FLYWHEEL / FLEXPLATE
add('FLYWHEEL', '飞轮', 'flywheel');
add('FLYWHEEL RING GEAR', '飞轮齿圈', 'giya ya mzingo ya flywheel');
add('RING GEAR', '齿圈', 'giya ya mzingo');
add('FLYWHEEL BEARING', '飞轮轴承', 'bearing ya flywheel');
add('FLYWHEEL BOLT', '飞轮螺丝', 'bolti ya flywheel');
add('FLYWHEEL KEY', '飞轮键', 'ufunguo wa flywheel');
add('FLEXPLATE', '飞轮盘', 'flexplate');
add('DUAL MASS FLYWHEEL', '双质量飞轮', 'flywheel ya molekuli mbili');
add('PILOT BEARING', '导向轴承', 'bearing ya mwongozo');
add('PILOT BUSHING', '导向套', 'bushi ya mwongozo');

// OIL SYSTEM
add('OIL PUMP', '机油泵', 'pampu ya mafuta');
add('OIL PUMP GASKET', '机油泵垫片', 'gasketi ya pampu ya mafuta');
add('OIL PUMP CHAIN', '机油泵链条', 'cheni ya pampu ya mafuta');
add('OIL PUMP DRIVE', '机油泵驱动', 'drive ya pampu ya mafuta');
add('OIL PUMP PICKUP', '机油泵吸管', 'kiingilio cha pampu ya mafuta');
add('OIL PUMP STRAINER', '机油泵滤网', 'chujio la pampu ya mafuta');
add('OIL PUMP RELIEF VALVE', '机油泵卸压阀', 'valvu ya kupunguza shinikizo');
add('OIL PAN', '油底壳', 'pani ya mafuta');
add('OIL PAN GASKET', '油底壳垫片', 'gasketi ya pani ya mafuta');
add('SUMP GASKET', '油底壳垫片', 'gasketi ya sump');
add('OIL PAN PLUG', '油底壳放油螺丝', 'plagi ya pani ya mafuta');
add('OIL DRAIN PLUG', '放油螺丝', 'plagi ya kutoa mafuta');
add('OIL LEVEL GAUGE', '机油尺', 'fimbo ya kupima mafuta');
add('OIL DIPSTICK', '机油尺', 'dipstick ya mafuta');
add('OIL DIPSTICK TUBE', '机油尺管', 'tube ya dipstick');
add('OIL LEVEL SENSOR', '机油液位传感器', 'sensa ya kiwango cha mafuta');
add('OIL PRESSURE SENSOR', '机油压力传感器', 'sensa ya shinikizo la mafuta');
add('OIL PRESSURE SWITCH', '机油压力开关', 'swichi ya shinikizo la mafuta');
add('OIL PRESSURE GAUGE', '机油压力表', 'geji ya shinikizo la mafuta');
add('OIL TEMPERATURE SENSOR', '机油温度传感器', 'sensa ya joto la mafuta');
add('OIL SWITCH', '机油开关', 'swichi ya mafuta');
add('OIL PRESSURE VALVE', '机油压力阀', 'valvu ya shinikizo la mafuta');
add('OIL FILTER', '机油滤清器', 'chujio la mafuta');
add('OIL FILTER HOUSING', '机油滤清器座', 'nyumba ya chujio la mafuta');
add('OIL FILTER GASKET', '机油滤清器垫片', 'gasketi ya chujio la mafuta');
add('OIL FILTER WRENCH', '机油滤清器扳手', 'spana ya chujio la mafuta');
add('OIL STRAINER', '机油滤网', 'chujio la mafuta');
add('OIL COOLER', '机油冷却器', 'kipozaji cha mafuta');
add('OIL COOLER HOSE', '机油冷却器软管', 'hose ya kipozaji cha mafuta');
add('OIL COOLER GASKET', '机油冷却器垫片', 'gasketi ya kipozaji cha mafuta');
add('OIL COOLER PIPE', '机油冷却器管', 'pipe ya kipozaji cha mafuta');
add('OIL GALLERY', '机油道', 'njia ya mafuta');
add('OIL PASSAGE', '机油道', 'njia ya mafuta');
add('OIL RETURN', '机油回路', 'njia ya kurudi ya mafuta');
add('OIL JET', '机油喷嘴', 'jeti ya mafuta');
add('OIL FILLER CAP', '机油加注口盖', 'kifuniko cha kujaza mafuta');
add('OIL FILLER NECK', '机油加注口', 'shingo ya kujaza mafuta');
add('OIL SLUDGE', '油泥', 'tope la mafuta');
add('OIL VISCOSITY', '机油粘度', 'mnato wa mafuta');
add('OIL CONSUMPTION', '机油消耗', 'matumizi ya mafuta');
add('OIL BURNING', '烧机油', 'kuchoma mafuta');
add('OIL LEAK', '漏油', 'kuvuja mafuta');

// CYLINDER HEAD GASKET / INTAKE / EXHAUST MANIFOLD GASKETS
add('HEAD GASKET SET', '缸垫套装', 'seti ya gasketi ya kichwa');
add('INTAKE MANIFOLD GASKET', '进气歧管垫片', 'gasketi ya intake');
add('INTAKE MANIFOLD', '进气歧管', 'intake manifold');
add('INTAKE MANIFOLD GASKET SET', '进气歧管垫片套装', 'seti ya gasketi ya intake');
add('INTAKE PIPE', '进气管', 'pipe ya kuingiza');
add('INTAKE HOSE', '进气软管', 'hose ya kuingiza');
add('INTAKE DUCT', '进气管', 'duct ya kuingiza');
add('INTAKE BOOT', '进气套', 'boot ya kuingiza');
add('AIR INTAKE', '进气系统', 'mfumo wa kuingiza hewa');
add('AIR INTAKE HOSE', '进气软管', 'hose ya kuingiza hewa');
add('AIR INTAKE TUBE', '进气歧管', 'tube ya kuingiza hewa');
add('AIR INTAKE RESONATOR', '进气谐振器', 'resonator ya kuingiza hewa');
add('INTAKE VALVE', '进气门', 'valvu ya kuingiza');
add('EXHAUST MANIFOLD GASKET', '排气歧管垫片', 'gasketi ya exhaust manifold');
add('EXHAUST MANIFOLD', '排气歧管', 'exhaust manifold');
add('EXHAUST GASKET', '排气管垫片', 'gasketi ya exhaust');
add('EXHAUST MANIFOLD BOLT', '排气歧管螺丝', 'bolti ya exhaust manifold');
add('EXHAUST MANIFOLD STUD', '排气歧管双头螺丝', 'stud ya exhaust manifold');
add('EXHAUST PIPE GASKET', '排气管垫片', 'gasketi ya pipe ya exhaust');
add('INTAKE MANIFOLD BOLT', '进气歧管螺丝', 'bolti ya intake manifold');

// OIL SEAL / GASKET / O-RING
add('OIL SEAL', '油封', 'seal ya mafuta');
add('FRONT OIL SEAL', '前油封', 'seal ya mbele');
add('REAR OIL SEAL', '后油封', 'seal ya nyuma');
add('VALVE STEM SEAL', '气门油封', 'seal ya valvu');
add('CRANKSHAFT OIL SEAL', '曲轴油封', 'seal ya crankshafti');
add('CAMSHAFT OIL SEAL', '凸轮轴油封', 'seal ya camshafti');
add('AXLE OIL SEAL', '半轴油封', 'seal ya axle');
add('DIFFERENTIAL OIL SEAL', '差速器油封', 'seal ya difu');
add('TRANSMISSION OIL SEAL', '变速箱油封', 'seal ya gearbox');
add('WHEEL SEAL', '轮毂油封', 'seal ya gurudumu');
add('PINION SEAL', '小齿轮油封', 'seal ya pinion');
add('GASKET', '垫片', 'gasketi');
add('RUBBER GASKET', '橡胶垫片', 'gasketi ya mpira');
add('CORK GASKET', '软木垫片', 'gasketi ya kork');
add('METAL GASKET', '金属垫片', 'gasketi ya chuma');
add('PAPER GASKET', '纸垫片', 'gasketi ya karatasi');
add('SILICONE GASKET', '硅胶垫片', 'gasketi ya silicone');
add('O-RING', 'O型密封圈', 'O-ringi');
add('RUBBER O-RING', '橡胶密封圈', 'O-ringi ya mpira');
add('SILICONE O-RING', '硅胶密封圈', 'O-ringi ya silicone');
add('WASHER', '垫圈', 'washer');
add('COPPER WASHER', '铜垫圈', 'washer ya shaba');
add('RUBBER WASHER', '橡胶垫圈', 'washer ya mpira');
add('SPRING WASHER', '弹簧垫圈', 'washer ya springi');
add('FLAT WASHER', '平垫圈', 'washer gorofa');
add('LOCK WASHER', '锁紧垫圈', 'washer ya kufunga');
add('THRUST WASHER', '止推垫圈', 'washer ya kusukuma');
add('SEAL', '密封件', 'seal');
add('SEAL KIT', '密封套装', 'seti ya seal');
add('SEAL RING', '密封环', 'peteya seal');
add('GASKET SET', '垫片套装', 'seti ya gasketi');
add('ENGINE GASKET KIT', '发动机垫片套装', 'seti ya gasketi ya injini');
add('TRANSMISSION GASKET KIT', '变速箱垫片套装', 'seti ya gasketi ya gearbox');
add('GASKET SEALANT', '密封胶', 'gundi ya gasketi');
add('SILICONE SEALANT', '硅胶密封胶', 'sealant ya silicone');

// ═══════════════════════════════════════════════════════════
// FUEL SYSTEM — 燃油系统 — MFUMO WA MAFUTA
// ═══════════════════════════════════════════════════════════
add('FUEL SYSTEM', '燃油系统', 'mfumo wa mafuta');
add('FUEL TANK', '油箱', 'tangi la mafuta');
add('FUEL CAP', '油箱盖', 'kifuniko cha tangi');
add('FUEL TANK CAP', '油箱盖', 'kifuniko cha tangi la mafuta');
add('FUEL TANK STRAP', '油箱绑带', 'kamba ya tangi');
add('FUEL TANK SENDER', '油位传感器', 'sensa ya kiwango cha mafuta');
add('FUEL GAUGE', '油量表', 'geji ya mafuta');
add('FUEL GAUGE UNIT', '油位传感器总成', 'kitengo cha geji ya mafuta');
add('FUEL LEVEL SENSOR', '油位传感器', 'sensa ya kiwango cha mafuta');
add('FUEL PUMP', '燃油泵', 'pampu ya mafuta');
add('FUEL PUMP ASSEMBLY', '燃油泵总成', 'pampu ya mafuta kamili');
add('FUEL PUMP MODULE', '燃油泵模块', 'moduli ya pampu');
add('FUEL PUMP RELAY', '燃油泵继电器', 'relay ya pampu ya mafuta');
add('FUEL PUMP STRAINER', '燃油泵滤网', 'chujio la pampu ya mafuta');
add('FUEL PUMP SEAL', '燃油泵密封圈', 'seal ya pampu ya mafuta');
add('FUEL PUMP GASKET', '燃油泵垫片', 'gasketi ya pampu ya mafuta');
add('ELECTRIC FUEL PUMP', '电动燃油泵', 'pampu ya mafuta ya umeme');
add('MECHANICAL FUEL PUMP', '机械燃油泵', 'pampu ya mafuta ya mitambo');
add('HIGH PRESSURE PUMP', '高压油泵', 'pampu ya shinikizo la juu');
add('HIGH PRESSURE FUEL PUMP', '高压燃油泵', 'pampu ya shinikizo la juu la mafuta');
add('INJECTION PUMP', '喷油泵', 'pampu ya injection');
add('DIESEL PUMP', '柴油泵', 'pampu ya dizeli');
add('LIFT PUMP', '输油泵', 'pampu ya kuinua');
add('TRANSFER PUMP', '输油泵', 'pampu ya kusafirisha');
add('FUEL FILTER', '燃油滤清器', 'chujio la mafuta');
add('DIESEL FILTER', '柴油滤清器', 'chujio la dizeli');
add('DIESEL FILTER COMPLETE', '柴油滤清器总成', 'chujio la dizeli kamili');
add('DIESEL FILTER ELEMENT', '柴油滤芯', 'elementi ya chujio la dizeli');
add('FUEL FILTER ELEMENT', '燃油滤芯', 'elementi ya chujio');
add('FUEL FILTER HOUSING', '燃油滤清器座', 'nyumba ya chujio');
add('FUEL FILTER CAP', '燃油滤清器盖', 'kifuniko cha chujio');
add('FUEL WATER SEPARATOR', '油水分离器', 'kitenganishi cha maji na mafuta');
add('FUEL INJECTOR', '喷油嘴', 'injector ya mafuta');
add('FUEL INJECTOR SEAL', '喷油嘴密封圈', 'seal ya injector');
add('FUEL INJECTOR O-RING', '喷油嘴O型圈', 'O-ringi ya injector');
add('FUEL INJECTOR CLIP', '喷油嘴卡子', 'kishikizo cha injector');
add('INJECTOR', '喷油嘴', 'injector');
add('INJECTION NOZZLE', '喷油嘴', 'nozzle ya injection');
add('NOZZLE', '喷油嘴', 'nozzle');
add('NOZZLE SEAL', '喷油嘴密封圈', 'seal ya nozzle');
add('NOZZLE TEST', '喷油嘴检测', 'kupima nozzle');
add('NOZZLE CLEANING', '喷油嘴清洗', 'kusafisha nozzle');
add('NOZZLE REPAIR', '喷油嘴维修', 'kutengeneza nozzle');
add('NOZZLE SPRING', '喷油嘴弹簧', 'springi ya nozzle');
add('NOZZLE HOLDER', '喷油嘴支架', 'kishikizi cha nozzle');
add('NOZZLE WASHER', '喷油嘴垫圈', 'washer ya nozzle');
add('FUEL INJECTOR CLEANER', '喷油嘴清洗剂', 'dawa ya kusafisha injector');
add('FUEL INJECTOR CLEANING', '喷油嘴清洗', 'kusafisha injector');
add('FUEL RAIL', '燃油导轨', 'reli ya mafuta');
add('FUEL RAIL PRESSURE SENSOR', '燃油压力传感器', 'sensa ya shinikizo la reli');
add('FUEL INJECTOR RAIL', '喷油嘴导轨', 'reli ya injector');
add('FUEL PRESSURE REGULATOR', '燃油压力调节器', 'regulator ya shinikizo la mafuta');
add('FUEL PRESSURE SENSOR', '燃油压力传感器', 'sensa ya shinikizo la mafuta');
add('FUEL PRESSURE GAUGE', '燃油压力表', 'geji ya shinikizo la mafuta');
add('FUEL PRESSURE DAMPER', '燃油压力减震器', 'damper ya shinikizo la mafuta');
add('FUEL PIPE', '燃油管', 'pipe ya mafuta');
add('FUEL HOSE', '燃油软管', 'hose ya mafuta');
add('FUEL LINE', '燃油管', 'laini ya mafuta');
add('FUEL RETURN HOSE', '回油管', 'hose ya kurudi ya mafuta');
add('FUEL RETURN LINE', '回油管', 'laini ya kurudi ya mafuta');
add('FUEL SUPPLY LINE', '供油管', 'laini ya kusambaza mafuta');
add('FUEL VAPOR HOSE', '燃油蒸汽管', 'hose ya mvuke ya mafuta');
add('FUEL BREATHER', '燃油通气口', 'kipumulia cha mafuta');
add('FUEL BREATHER VALVE', '燃油通气阀', 'valvu ya kupumulia');
add('FUEL SHUTOFF VALVE', '燃油切断阀', 'valvu ya kukata mafuta');
add('FUEL CHECK VALVE', '燃油单向阀', 'valvu ya kuzuia mafuta');
add('FUEL SOLENOID', '燃油电磁阀', 'solenoidi ya mafuta');
add('FUEL CUT SOLENOID', '断油电磁阀', 'solenoidi ya kukata mafuta');
add('FUEL SOLENOID VALVE', '燃油电磁阀', 'valvu ya solenoidi ya mafuta');
add('CARBURETOR', '化油器', 'carburetor');
add('CARBURETOR GASKET', '化油器垫片', 'gasketi ya carburetor');
add('CARBURETOR REPAIR KIT', '化油器维修包', 'seti ya kutengeneza carburetor');
add('CARBURETOR FLOAT', '化油器浮子', 'floti ya carburetor');
add('CARBURETOR JET', '化油器量孔', 'jeti ya carburetor');
add('CARBURETOR NEEDLE', '化油器针阀', 'sindano ya carburetor');
add('CARBURETOR CLEANER', '化油器清洗剂', 'dawa ya kusafisha carburetor');
add('CARB CHOKE CLEANER', '化油器清洗剂', 'dawa ya kusafisha carburetor');
add('CHOKE', '阻风门', 'choki');
add('CHOKE VALVE', '阻风门', 'valvu ya choki');
add('THROTTLE BODY', '节气门', 'throttle body');
add('THROTTLE BODY GASKET', '节气门垫片', 'gasketi ya throttle body');
add('THROTTLE BODY CLEANER', '节气门清洗剂', 'dawa ya kusafisha throttle');
add('THROTTLE BODY CLEANING', '节气门清洗', 'kusafisha throttle body');
add('THROTTLE VALVE', '节气门', 'valvu ya throttle');
add('THROTTLE CABLE', '油门拉线', 'kebo ya throttle');
add('THROTTLE POSITION SENSOR', '节气门位置传感器', 'sensa ya nafasi ya throttle');
add('THROTTLE ACTUATOR', '节气门执行器', 'actuator ya throttle');
add('ACCELERATOR PEDAL', '油门踏板', 'pedali ya kuongeza mwendo');
add('ACCELERATOR CABLE', '油门拉线', 'kebo ya accelerator');
add('GAS PEDAL', '油门踏板', 'pedali ya gesi');
add('IDLE AIR CONTROL VALVE', '怠速控制阀', 'valvu ya kudhibiti idle');
add('IDLE CONTROL VALVE', '怠速控制阀', 'valvu ya idle');
add('IDLE AIR CONTROL', '怠速控制', 'udhibiti wa idle');
add('IDLE SPEED CONTROL', '怠速控制', 'udhibiti wa kasi ya idle');
add('IDLE SPEED MOTOR', '怠速马达', 'mota ya idle');
add('AIR CONTROL VALVE', '空气控制阀', 'valvu ya kudhibiti hewa');

// AIR INTAKE / FILTER
add('AIR CLEANER', '空气滤清器总成', 'chujio la hewa');
add('AIR CLEANER ELEMENT', '空气滤芯', 'elementi ya chujio la hewa');
add('AIR CLEANER COVER', '空气滤清器盖', 'kifuniko cha chujio la hewa');
add('AIR CLEANER HOUSING', '空气滤清器壳体', 'nyumba ya chujio la hewa');
add('AIR CLEANER PIPE', '空气滤清器管', 'pipe ya chujio la hewa');
add('AIR CLEANER HOSE', '空气滤清器软管', 'hose ya chujio la hewa');
add('AIR FILTER', '空气滤清器', 'chujio la hewa');
add('AIR FILTER ELEMENT', '空气滤芯', 'elementi ya chujio la hewa');
add('AIR FILTER BOX', '空气滤清器盒子', 'sanduku la chujio la hewa');
add('AIR FILTER COVER', '空气滤清器盖', 'kifuniko cha chujio la hewa');
add('AIR FILTER HOUSING', '空气滤清器座', 'nyumba ya chujio la hewa');
add('PERFORMANCE AIR FILTER', '高性能空气滤清器', 'chujio la hewa bora');
add('SPORTS AIR FILTER', '运动型空气滤清器', 'chujio la hewa la sport');
add('AIR MASS METER', '空气流量计', 'mita ya hewa');
add('AIR FLOW SENSOR', '空气流量传感器', 'sensa ya mtiririko wa hewa');
add('MASS AIR FLOW SENSOR', '空气流量传感器', 'MAF sensa');
add('MAP SENSOR', '进气压力传感器', 'sensa ya MAP');
add('MANIFOLD ABSOLUTE PRESSURE SENSOR', '绝对压力传感器', 'sensa ya shinikizo kamili');
add('INTAKE AIR TEMPERATURE SENSOR', '进气温度传感器', 'sensa ya joto la hewa');
add('AIR TEMPERATURE SENSOR', '空气温度传感器', 'sensa ya joto la hewa');
add('BOOST PRESSURE SENSOR', '增压压力传感器', 'sensa ya shinikizo la boost');
add('TURBO PRESSURE SENSOR', '涡轮压力传感器', 'sensa ya shinikizo la turbo');
add('AIR FILTER CLEANING KIT', '空气滤清器清洗套装', 'seti ya kusafisha chujio la hewa');

// CATALYTIC CONVERTER
add('CATALYTIC CONVERTER', '三元催化器', 'catalytic converter');
add('CATALYTIC CONVERTER GASKET', '三元催化器垫片', 'gasketi ya catalytic converter');
add('DIESEL PARTICULATE FILTER', '柴油颗粒过滤器', 'chujio la chembe za dizeli');
add('DPF', '柴油颗粒过滤器', 'DPF');
add('DPF CLEANING', 'DPF清洗', 'kusafisha DPF');
add('DPF REGENERATION', 'DPF再生', 'kuzalisha upya DPF');
add('EGR VALVE', '废气再循环阀', 'valvu ya EGR');
add('EGR TUBE', '废气再循环管', 'tube ya EGR');
add('EGR COOLER', '废气再循环冷却器', 'kipozaji cha EGR');
add('EGR GASKET', '废气再循环垫片', 'gasketi ya EGR');
add('EGR SYSTEM', '废气再循环系统', 'mfumo wa EGR');

// EXHAUST
add('EXHAUST SYSTEM', '排气系统', 'mfumo wa exhaust');
add('EXHAUST PIPE', '排气管', 'pipe ya exhaust');
add('EXHAUST MUFFLER', '消声器', 'muffler');
add('MUFFLER', '消声器', 'muffler');
add('SILENCER', '消声器', 'silencer');
add('EXHAUST TIP', '排气尾喉', 'ncha ya exhaust');
add('TAILPIPE', '排气管尾段', 'mrija wa nyuma');
add('EXHAUST BRACKET', '排气管支架', 'bracket ya exhaust');
add('EXHAUST CLAMP', '排气管卡箍', 'clamp ya exhaust');
add('EXHAUST HANGER', '排气管吊耳', 'hanger ya exhaust');
add('EXHAUST RUBBER', '排气管吊耳橡胶', 'mpira wa exhaust');
add('EXHAUST MOUNT', '排气管支架', 'mount ya exhaust');
add('EXHAUST GASKET', '排气管垫片', 'gasketi ya exhaust');
add('EXHAUST DONUT GASKET', '排气管环形垫片', 'gasketi ya donut');
add('EXHAUST FLANGE', '排气管法兰', 'flange ya exhaust');
add('EXHAUST FLANGE GASKET', '排气管法兰垫片', 'gasketi ya flange ya exhaust');
add('EXHAUST RESONATOR', '排气谐振器', 'resonator ya exhaust');
add('FLEX PIPE', '排气管软连接', 'pipe ya flex');
add('EXHAUST FLEX JOINT', '排气管软接头', 'jointi ya flex');
add('EXHAUST LEAK', '排气管漏气', 'kuvuja exhaust');
add('CATALYTIC CONVERTER CLEANER', '三元催化清洗剂', 'dawa ya kusafisha catalytic');
add('PCV VALVE', '曲轴箱通风阀', 'valvu ya PCV');
add('BREATHER VALVE', '通风阀', 'valvu ya kupumulia');
add('BREATHER PIPE', '通风管', 'pipe ya kupumulia');
add('BREATHER HOSE', '通风软管', 'hose ya kupumulia');

// ═══════════════════════════════════════════════════════════
// COOLING SYSTEM — 冷却系统 — MFUMO WA KUPOZA
// ═══════════════════════════════════════════════════════════
add('COOLING SYSTEM', '冷却系统', 'mfumo wa kupoza');
add('RADIATOR', '水箱', 'redieta');
add('RADIATOR ASSEMBLY', '水箱总成', 'redieta kamili');
add('RADIATOR CORE', '水箱芯', 'kini ya redieta');
add('RADIATOR CAP', '水箱盖', 'kifuniko cha redieta');
add('RADIATOR PRESSURE CAP', '水箱压力盖', 'kifuniko cha shinikizo');
add('RADIATOR CAP GASKET', '水箱盖垫片', 'gasketi ya kifuniko cha redieta');
add('RADIATOR HOSE', '水箱管', 'hose ya redieta');
add('RADIATOR HOSE UPPER', '水箱上水管', 'hose ya juu ya redieta');
add('RADIATOR HOSE LOWER', '水箱下水管', 'hose ya chini ya redieta');
add('RADIATOR MOUNTING', '水箱支架', 'mount ya redieta');
add('RADIATOR BRACKET', '水箱支架', 'bracket ya redieta');
add('RADIATOR FAN', '散热风扇', 'feni ya redieta');
add('RADIATOR FAN ASSEMBLY', '散热风扇总成', 'feni ya redieta kamili');
add('RADIATOR FAN MOTOR', '散热风扇电机', 'mota ya feni ya redieta');
add('RADIATOR FAN BLADE', '散热风扇叶片', 'blade ya feni ya redieta');
add('RADIATOR FAN SHROUD', '散热风扇罩', 'kifuniko cha feni');
add('RADIATOR FAN SWITCH', '散热风扇开关', 'switchi ya feni');
add('RADIATOR FAN RESISTOR', '散热风扇电阻', 'resistor ya feni');
add('RADIATOR FAN RELAY', '散热风扇继电器', 'relay ya feni');
add('RADIATOR FAN CONTROL MODULE', '散热风扇控制模块', 'moduli ya feni');
add('AUXILIARY RADIATOR', '副水箱', 'redieta ya ziada');
add('RADIATOR OVERFLOW TANK', '副水壶', 'tangi la kufurika');
add('EXPANSION TANK', '膨胀水箱', 'tangi la upanuzi');
add('COOLANT RESERVOIR', '冷却液壶', 'chombo cha coolant');
add('COOLANT OVERFLOW TANK', '冷却液溢流壶', 'tangi la kufurika la coolant');
add('WATER PUMP', '水泵', 'pampu ya maji');
add('WATER PUMP GASKET', '水泵垫片', 'gasketi ya pampu ya maji');
add('WATER PUMP SEAL', '水泵密封圈', 'seal ya pampu ya maji');
add('WATER PUMP PULLEY', '水泵皮带轮', 'pulley ya pampu ya maji');
add('WATER PUMP BELT', '水泵皮带', 'mkanda wa pampu ya maji');
add('WATER PUMP BEARING', '水泵轴承', 'bearing ya pampu ya maji');
add('WATER PUMP IMPELLER', '水泵叶轮', 'impeller ya pampu');
add('WATER PUMP HOUSING', '水泵壳体', 'nyumba ya pampu ya maji');
add('WATER PUMP INLET', '水泵进水口', 'kiingilio cha pampu');
add('WATER PUMP OUTLET', '水泵出水口', 'kutolea cha pampu');
add('WATER HOSE', '水管', 'hose ya maji');
add('WATER PIPE', '水管', 'pipe ya maji');
add('WATER OUTLET', '出水口', 'kutolea maji');
add('WATER INLET', '进水口', 'kiingilio cha maji');
add('WATER BYPASS HOSE', '旁通水管', 'hose ya bypass ya maji');
add('WATER BYPASS PIPE', '旁通水管', 'pipe ya bypass ya maji');
add('HEATER HOSE', '暖风水管', 'hose ya heater');
add('HEATER PIPE', '暖风管', 'pipe ya heater');
add('COOLANT HOSE', '冷却液软管', 'hose ya coolant');
add('COOLANT PIPE', '冷却液管', 'pipe ya coolant');
add('THERMOSTAT', '节温器', 'thermostat');
add('THERMOSTAT GASKET', '节温器垫片', 'gasketi ya thermostat');
add('THERMOSTAT SEAL', '节温器密封圈', 'seal ya thermostat');
add('THERMOSTAT HOUSING', '节温器座', 'nyumba ya thermostat');
add('THERMOSTAT O-RING', '节温器O型圈', 'O-ringi ya thermostat');
add('COOLANT TEMPERATURE SENSOR', '水温传感器', 'sensa ya joto la coolant');
add('WATER TEMPERATURE SENSOR', '水温传感器', 'sensa ya joto la maji');
add('COOLANT TEMPERATURE GAUGE', '水温表', 'geji ya joto la coolant');
add('TEMPERATURE SENSOR', '温度传感器', 'sensa ya joto');
add('COOLING FAN', '冷却风扇', 'feni ya kupoza');
add('AC FAN', '空调风扇', 'feni ya AC');
add('CONDENSER FAN', '冷凝器风扇', 'feni ya condenser');
add('FAN CLUTCH', '风扇离合器', 'clutch ya feni');
add('FAN BLADE', '风扇叶片', 'blade ya feni');
add('FAN COUPLING', '风扇耦合器', 'coupling ya feni');
add('ELECTRIC FAN', '电子风扇', 'feni ya umeme');
add('COOLANT', '冷却液', 'coolant');
add('ANTIFREEZE', '防冻液', 'antifreeze');
add('RADIATOR COOLANT', '水箱冷却液', 'coolant ya redieta');
add('RADIATOR COOLANT 1 LITRE', '水箱冷却液1升', 'coolant ya redieta lita 1');
add('RADIATOR COOLANT 4 LITRES', '水箱冷却液4升', 'coolant ya redieta lita 4');
add('RADIATOR COOLANT 5 LITRES', '水箱冷却液5升', 'coolant ya redieta lita 5');
add('RADIATOR COOLANT CONCENTRATE', '冷却液浓缩液', 'coolant iliyokolea');
add('COOLANT FLUSH', '冷却液清洗', 'kusafisha coolant');
add('RADIATOR FLUSH', '水箱清洗', 'kusafisha redieta');
add('COOLANT LEAK', '冷却液泄漏', 'kuvuja coolant');
add('RADIATOR LEAK', '水箱漏水', 'redieta kuvuja');
add('RADIATOR STOP LEAK', '水箱堵漏剂', 'dawa ya kuzuia kuvuja');
add('COOLANT ADDITIVE', '冷却液添加剂', 'kiongezi cha coolant');
add('WATER WETTER', '冷却液增效剂', 'kiboresha kupoza maji');

// ═══════════════════════════════════════════════════════════
// ELECTRICAL / IGNITION — 电器/点火 — UMEME
// ═══════════════════════════════════════════════════════════
add('ALTERNATOR', '发电机', 'alterneta');
add('ALTERNATOR ASSEMBLY', '发电机总成', 'alterneta kamili');
add('ALTERNATOR PULLEY', '发电机皮带轮', 'pulley ya alterneta');
add('ALTERNATOR BELT', '发电机皮带', 'mkanda wa alterneta');
add('ALTERNATOR BRACKET', '发电机支架', 'bracket ya alterneta');
add('ALTERNATOR BRUSH', '发电机碳刷', 'brashi ya alterneta');
add('ALTERNATOR REGULATOR', '发电机调节器', 'regulator ya alterneta');
add('ALTERNATOR VOLTAGE REGULATOR', '发电机电压调节器', 'regulator ya voltage');
add('ALTERNATOR RECTIFIER', '发电机整流器', 'rectifier ya alterneta');
add('ALTERNATOR DIODE', '发电机二极管', 'diode ya alterneta');
add('ALTERNATOR BEARING', '发电机轴承', 'bearing ya alterneta');
add('ALTERNATOR ROTOR', '发电机转子', 'rota ya alterneta');
add('ALTERNATOR STATOR', '发电机定子', 'stator ya alterneta');
add('ALTERNATOR REPAIR', '发电机维修', 'kutengeneza alterneta');
add('STARTER', '启动机', 'starter');
add('STARTER MOTOR', '启动马达', 'starter motor');
add('STARTER ASSEMBLY', '启动机总成', 'starter kamili');
add('STARTER BRUSH', '启动机碳刷', 'brashi ya starter');
add('STARTER BRUSH HOLDER', '启动机碳刷架', 'kishikizi cha brashi');
add('STARTER SOLENOID', '启动机电磁开关', 'solenoidi ya starter');
add('STARTER RELAY', '启动继电器', 'relay ya starter');
add('STARTER BENDIX', '启动机齿轮', 'bendix');
add('STARTER DRIVE', '启动机驱动齿轮', 'drive ya starter');
add('STARTER PINION', '启动机小齿轮', 'pinion ya starter');
add('STARTER CLUTCH', '启动机单向离合器', 'clutch ya starter');
add('STARTER ARMATURE', '启动机电枢', 'armature ya starter');
add('STARTER FIELD COIL', '启动机磁场线圈', 'coil ya starter');
add('STARTER BUSHING', '启动机轴套', 'bushi ya starter');
add('STARTER REPAIR', '启动机维修', 'kutengeneza starter');
add('BATTERY', '电瓶', 'betri');
add('BATTERY TERMINAL', '电瓶桩头', 'terminal ya betri');
add('BATTERY TERMINAL POSITIVE', '电瓶正极', 'terminal chanya');
add('BATTERY TERMINAL NEGATIVE', '电瓶负极', 'terminal hasi');
add('BATTERY CLAMP', '电瓶夹子', 'clamp ya betri');
add('BATTERY CABLE POSITIVE', '电瓶正极线', 'kebo chanya');
add('BATTERY CABLE NEGATIVE', '电瓶负极线', 'kebo hasi');
add('BATTERY CABLE', '电瓶线', 'kebo ya betri');
add('BATTERY TRAY', '电瓶托盘', 'tray ya betri');
add('BATTERY HOLD DOWN', '电瓶固定架', 'kifungio cha betri');
add('BATTERY WATER', '电瓶水', 'maji ya betri');
add('BATTERY ACID', '电瓶液', 'asidi ya betri');
add('BATTERY CHARGER', '电瓶充电器', 'chaja ya betri');
add('BATTERY TEST', '电瓶检测', 'kupima betri');
add('BATTERY REPLACEMENT', '更换电瓶', 'kubadilisha betri');
add('BATTERY JUMP START', '电瓶搭电', 'kupasha moto betri');
add('BATTERY N50', '电瓶N50', 'betri N50');
add('BATTERY N70', '电瓶N70', 'betri N70');
add('BATTERY N70L', '电瓶N70L', 'betri N70L');
add('BATTERY NS60', '电瓶NS60', 'betri NS60');
add('BATTERY NS70', '电瓶NS70', 'betri NS70');
add('DRY BATTERY', '干电瓶', 'betri kavu');
add('MAINTENANCE FREE BATTERY', '免维护电瓶', 'betri isiyotunzwa');
add('COLD CRANKING AMP', '冷启动电流', 'CCA');
add('SPARK PLUG', '火花塞', 'spark plug');
add('SPARK PLUG SET', '火花塞组', 'seti ya spark plug');
add('SPARK PLUG GAP', '火花塞间隙', 'nafasi ya spark plug');
add('SPARK PLUG WIRE', '高压线', 'waya ya spark plug');
add('SPARK PLUG WIRE SET', '高压线组', 'seti ya waya za spark plug');
add('SPARK PLUG SOCKET', '火花塞套筒', 'spana ya spark plug');
add('SPARK PLUG REPLACEMENT', '更换火花塞', 'kubadilisha spark plug');
add('IRIDIUM SPARK PLUG', '铱金火花塞', 'spark plug ya iridium');
add('PLATINUM SPARK PLUG', '铂金火花塞', 'spark plug ya platinum');
add('GLOW PLUG', '预热塞', 'glow plug');
add('GLOW PLUG RELAY', '预热塞继电器', 'relay ya glow plug');
add('GLOW PLUG MODULE', '预热控制模块', 'moduli ya glow plug');
add('IGNITION COIL', '点火线圈', 'coil ya ignition');
add('IGNITION COIL PACK', '点火线圈组', 'pack ya coil ya ignition');
add('IGNITION COIL BOOT', '点火线圈胶套', 'boot ya coil');
add('IGNITION COIL CONNECTOR', '点火线圈插头', 'connector ya coil');
add('IGNITION COIL MODULE', '点火模块', 'moduli ya ignition');
add('IGNITION MODULE', '点火模块', 'moduli ya ignition');
add('IGNITION TIMING', '点火正时', 'timing ya ignition');
add('IGNITION WIRE', '高压线', 'waya ya ignition');
add('IGNITION CABLE', '高压线', 'kebo ya ignition');
add('IGNITION SWITCH', '点火开关', 'switchi ya ignition');
add('IGNITION KEY', '点火钥匙', 'ufunguo wa ignition');
add('IGNITION LOCK', '点火锁', 'kufuli ya ignition');
add('IGNITION RELAY', '点火继电器', 'relay ya ignition');
add('DISTRIBUTOR', '分电器', 'distributor');
add('DISTRIBUTOR CAP', '分电器盖', 'kifuniko cha distributor');
add('DISTRIBUTOR ROTOR', '分火头', 'rota ya distributor');
add('DISTRIBUTOR O-RING', '分电器O型圈', 'O-ringi ya distributor');
add('DISTRIBUTOR PICKUP', '分电器传感器', 'pickup ya distributor');
add('DISTRIBUTOR POINTS', '分电器白金触点', 'points za distributor');
add('DISTRIBUTOR CONDENSER', '电容器', 'condenser');
add('IGNITION POINTS', '点火白金', 'points za ignition');
add('IGNITION CONDENSER', '点火电容器', 'condenser ya ignition');
add('COIL WIRE', '高压线', 'waya ya coil');

// SENSORS
add('SENSOR', '传感器', 'sensa');
add('OXYGEN SENSOR', '氧传感器', 'sensa ya oksijeni');
add('O2 SENSOR', '氧传感器', 'sensa ya O2');
add('FRONT OXYGEN SENSOR', '前氧传感器', 'sensa ya oksijeni ya mbele');
add('REAR OXYGEN SENSOR', '后氧传感器', 'sensa ya oksijeni ya nyuma');
add('KNOCK SENSOR', '爆震传感器', 'sensa ya kugonga');
add('CRANKSHAFT POSITION SENSOR', '曲轴位置传感器', 'CKP sensa');
add('CAMSHAFT POSITION SENSOR', '凸轮轴位置传感器', 'CMP sensa');
add('VEHICLE SPEED SENSOR', '车速传感器', 'sensa ya kasi');
add('SPEED SENSOR', '速度传感器', 'sensa ya kasi');
add('ABS SENSOR', 'ABS传感器', 'sensa ya ABS');
add('WHEEL SPEED SENSOR', '轮速传感器', 'sensa ya kasi ya gurudumu');
add('TIRE PRESSURE SENSOR', '胎压传感器', 'TPMS sensa');
add('TPMS SENSOR', '胎压监测传感器', 'sensa ya TPMS');
add('REVERSE SENSOR', '倒车雷达传感器', 'sensa ya nyuma');
add('PARKING SENSOR', '倒车雷达', 'sensa ya kuegesha');
add('PARKING AID', '倒车雷达', 'msaidizi wa kuegesha');
add('REVERSE CAMERA', '倒车影像', 'kamera ya nyuma');
add('BACKUP CAMERA', '倒车摄像头', 'kamera ya nyuma');
add('MASS AIR FLOW SENSOR', '空气流量计', 'MAF sensa');
add('THROTTLE POSITION SENSOR', '节气门位置传感器', 'TPS sensa');
add('COOLANT TEMPERATURE SENSOR', '冷却液温度传感器', 'CTS sensa');
add('INTAKE AIR TEMPERATURE SENSOR', '进气温度传感器', 'IAT sensa');
add('OIL PRESSURE SENSOR', '机油压力传感器', 'sensa ya shinikizo la mafuta');
add('FUEL LEVEL SENSOR', '油位传感器', 'sensa ya kiwango cha mafuta');
add('FUEL PRESSURE SENSOR', '燃油压力传感器', 'sensa ya shinikizo la mafuta');
add('FUEL RAIL PRESSURE SENSOR', '油轨压力传感器', 'sensa ya shinikizo la reli');
add('BOOST SENSOR', '增压传感器', 'sensa ya boost');
add('AMBIENT TEMPERATURE SENSOR', '环境温度传感器', 'sensa ya joto la nje');
add('RAIN SENSOR', '雨量传感器', 'sensa ya mvua');
add('LIGHT SENSOR', '光线传感器', 'sensa ya mwanga');
add('STEERING ANGLE SENSOR', '转向角传感器', 'sensa ya pembe ya usukani');
add('YAW RATE SENSOR', '横摆率传感器', 'sensa ya yaw');
add('ACCELERATION SENSOR', '加速度传感器', 'sensa ya kuongeza kasi');
add('G-FORCE SENSOR', 'G力传感器', 'sensa ya nguvu G');
add('PRESSURE SENSOR', '压力传感器', 'sensa ya shinikizo');
add('TEMPERATURE SENSOR', '温度传感器', 'sensa ya joto');
add('LEVEL SENSOR', '液位传感器', 'sensa ya kiwango');
add('POSITION SENSOR', '位置传感器', 'sensa ya nafasi');
add('TRANSMISSION SPEED SENSOR', '变速箱速度传感器', 'sensa ya kasi ya gearbox');

// ═══════════════════════════════════════════════════════════
// TRANSMISSION / CLUTCH — 变速箱/离合器 — GEARBOX / CLUTCH
// ═══════════════════════════════════════════════════════════
add('TRANSMISSION','变速箱','gearbox');
add('TRANSMISSION ASSEMBLY','变速箱总成','gearbox kamili');
add('TRANSMISSION FLUID','变速箱油','mafuta ya gearbox');
add('TRANSMISSION OIL','变速箱油','mafuta ya gearbox');
add('AUTOMATIC TRANSMISSION FLUID','自动变速箱油','mafuta ya gearbox otomatiki');
add('ATF FLUID','自动变速箱油','mafuta ya ATF');
add('MANUAL TRANSMISSION FLUID','手动变速箱油','mafuta ya gearbox manual');
add('GEAR OIL','齿轮油','mafuta ya giya');
add('GEAR BOX OIL','齿轮箱油','mafuta ya gearbox');
add('GEAR BOX OIL 1 LITRE','齿轮油1升','mafuta ya gearbox lita 1');
add('GEAR BOX OIL 4 LITRES','齿轮油4升','mafuta ya gearbox lita 4');
add('GEAR BOX OIL 5 LITRES','齿轮油5升','mafuta ya gearbox lita 5');
add('DIFFERENTIAL OIL','差速器油','mafuta ya difu');
add('DIFFERENTIAL FLUID','差速器油','mafuta ya difu');
add('TRANSMISSION PAN','变速箱油底壳','pani ya gearbox');
add('TRANSMISSION PAN GASKET','变速箱油底壳垫片','gasketi ya pani ya gearbox');
add('TRANSMISSION FILTER','变速箱滤清器','chujio la gearbox');
add('TRANSMISSION FILTER KIT','变速箱滤清器套装','seti ya chujio la gearbox');
add('TRANSMISSION COOLER','变速箱冷却器','kipozaji cha gearbox');
add('TRANSMISSION COOLER HOSE','变速箱散热管','hose ya kipozaji cha gearbox');
add('TRANSMISSION OIL COOLER','变速箱油冷器','kipozaji cha mafuta ya gearbox');
add('TRANSMISSION MOUNT','变速箱支架','mounti ya gearbox');
add('TRANSMISSION MOUNTING','变速箱支架','mounti ya gearbox');
add('TRANSMISSION MOUNT BRACKET','变速箱支架底座','bracket ya mounti ya gearbox');
add('TRANSMISSION SEAL','变速箱油封','seal ya gearbox');
add('TRANSMISSION INPUT SEAL','变速箱输入轴油封','seal ya kuingiza gearbox');
add('TRANSMISSION OUTPUT SEAL','变速箱输出轴油封','seal ya kutoa gearbox');
add('TRANSMISSION TAIL SHAFT SEAL','变速箱尾轴油封','seal ya tail shaft');
add('TRANSMISSION GASKET','变速箱垫片','gasketi ya gearbox');
add('TRANSMISSION GASKET KIT','变速箱垫片套装','seti ya gasketi ya gearbox');
add('AUTOMATIC TRANSMISSION GASKET KIT','自动变速箱垫片套装','seti ya gasketi ya gearbox otomatiki');
add('TRANSMISSION SOLENOID','变速箱电磁阀','solenoidi ya gearbox');
add('TRANSMISSION SOLENOID PACK','变速箱电磁阀组','pack ya solenoidi');
add('TRANSMISSION VALVE BODY','变速箱阀体','valve body ya gearbox');
add('TRANSMISSION CONTROL UNIT','变速箱控制单元','TCU');
add('TRANSMISSION CONTROL MODULE','变速箱控制模块','moduli ya gearbox');
add('TRANSMISSION SENSOR','变速箱传感器','sensa ya gearbox');
add('TRANSMISSION RANGE SENSOR','变速箱档位传感器','sensa ya range ya gearbox');
add('TRANSMISSION NEUTRAL SAFETY SWITCH','空档安全开关','switchi ya neutral');
add('TRANSMISSION SHIFT CABLE','变速箱换档拉线','kebo ya kushift gearbox');
add('TRANSMISSION SHIFT LEVER','换档杆','lever ya kushift');
add('GEAR SELECTOR','换档机构','kichagua giya');
add('SHIFT LEVER','换档杆','lever ya kushift');
add('SHIFT KNOB','排档头','knob ya kushift');
add('SHIFT BOOT','排档防尘套','boot ya kushift');
add('SHIFT CABLE','换档拉线','kebo ya kushift');
add('SHIFT LINKAGE','换档连杆','linkage ya kushift');
add('SHIFTER ASSEMBLY','换档总成','shifter kamili');
add('AUTOMATIC TRANSMISSION','自动变速箱','gearbox otomatiki');
add('MANUAL TRANSMISSION','手动变速箱','gearbox manual');
add('CONTINUOUSLY VARIABLE TRANSMISSION','无级变速箱','CVT');
add('CVT TRANSMISSION','CVT变速箱','gearbox CVT');
add('CVT FLUID','CVT变速箱油','mafuta ya CVT');
add('CVT BELT','CVT钢带','mkanda wa CVT');
add('CVT CHAIN','CVT链条','cheni ya CVT');
add('DUAL CLUTCH TRANSMISSION','双离合变速箱','DCT');
add('AUTOMATED MANUAL TRANSMISSION','自动手动变速箱','AMT');
add('TRANSAXLE','驱动桥变速箱','transaxle');
add('TRANSFER CASE','分动箱','transfer case');
add('TRANSFER CASE OIL','分动箱油','mafuta ya transfer case');
add('TRANSFER CASE SEAL','分动箱油封','seal ya transfer case');
add('TRANSFER CASE MOTOR','分动箱电机','mota ya transfer case');
add('TRANSFER CASE CHAIN','分动箱链条','cheni ya transfer case');
add('TRANSMISSION REBUILD','变速箱大修','kujenga upya gearbox');
add('TRANSMISSION OVERHAUL','变速箱大修','overhaul ya gearbox');
add('TRANSMISSION FLUSH','变速箱清洗','kusafisha gearbox');
add('TRANSMISSION REPAIR','变速箱维修','kutengeneza gearbox');

// CLUTCH
add('CLUTCH','离合器','clutch');
add('CLUTCH KIT','离合器套装','seti ya clutch');
add('CLUTCH SET','离合器三件套','seti ya clutch');
add('CLUTCH DISC','离合器片','disc ya clutch');
add('CLUTCH PLATE','离合器片','plate ya clutch');
add('CLUTCH COVER','离合器压盘','kifuniko cha clutch');
add('CLUTCH PRESSURE PLATE','离合器压盘','pressure plate');
add('PRESSURE PLATE','压盘','pressure plate');
add('CLUTCH RELEASE BEARING','离合器分离轴承','bearing ya kutolea');
add('RELEASE BEARING','分离轴承','bearing ya kutolea');
add('CLUTCH BEARING','离合器轴承','bearing ya clutch');
add('CLUTCH PILOT BEARING','导向轴承','bearing ya mwongozo');
add('CLUTCH CABLE','离合器拉线','kebo ya clutch');
add('CLUTCH HOSE','离合器软管','hose ya clutch');
add('CLUTCH PIPE','离合器管','pipe ya clutch');
add('CLUTCH FORK','离合器拨叉','fork ya clutch');
add('CLUTCH PEDAL','离合器踏板','pedali ya clutch');
add('CLUTCH MASTER CYLINDER','离合器总泵','master cylinder ya clutch');
add('CLUTCH SLAVE CYLINDER','离合器分泵','slave cylinder ya clutch');
add('CLUTCH CYLINDER','离合器分泵','cylinder ya clutch');
add('CLUTCH SLAVE','离合器分泵','slave ya clutch');
add('CLUTCH FLUID','离合器油','mafuta ya clutch');
add('CLUTCH RESERVOIR','离合器油壶','chombo cha clutch');
add('CLUTCH FLYWHEEL','离合器飞轮','flywheel ya clutch');
add('CLUTCH ALIGNMENT TOOL','离合器对中工具','chombo cha kupangilia clutch');
add('CLUTCH ADJUSTMENT','离合器调整','kurekebisha clutch');
add('CLUTCH BLEEDING','离合器排气','kutoa hewa clutch');
add('CLUTCH SLIPPING','离合器打滑','clutch kuteleza');

// ═══════════════════════════════════════════════════════════
// DRIVETRAIN / AXLE — 传动系统/车桥 — DRIVETRAIN
// ═══════════════════════════════════════════════════════════
add('DRIVETRAIN','传动系统','drivetrain');
add('DRIVE SHAFT','传动轴','shafti ya kusukuma');
add('PROPELLER SHAFT','传动轴','propeller shaft');
add('TAIL SHAFT','尾轴','tail shaft');
add('CENTER BEARING','过桥轴承','bearing ya kati');
add('CENTER SUPPORT BEARING','中间支撑轴承','bearing ya msaada wa kati');
add('UNIVERSAL JOINT','万向节','jointi universal');
add('U-JOINT','十字轴','U-jointi');
add('U-JOINT BEARING','十字轴轴承','bearing ya U-jointi');
add('CARDAN SHAFT','传动轴','cardan shaft');
add('CARDAN JOINT','万向节','jointi ya cardan');
add('DRIVE AXLE','驱动桥','axle ya kusukuma');
add('AXLE','车轴','axle');
add('AXLE SHAFT','半轴','shafti ya axle');
add('CV AXLE','球笼半轴','CV axle');
add('CV JOINT','球笼','jointi CV');
add('CV BOOT','球笼防尘套','boot ya CV');
add('CV JOINT KIT','球笼维修包','seti ya jointi CV');
add('CV JOINT GREASE','球笼润滑脂','grisi ya jointi CV');
add('OUTER CV JOINT','外球笼','jointi CV ya nje');
add('INNER CV JOINT','内球笼','jointi CV ya ndani');
add('CV JOINT BOOT','球笼套','boot ya jointi CV');
add('AXLE SEAL','半轴油封','seal ya axle');
add('AXLE OIL SEAL','半轴油封','seal ya mafuta ya axle');
add('AXLE BEARING','半轴轴承','bearing ya axle');
add('AXLE NUT','半轴螺母','nati ya axle');
add('REAR AXLE','后桥','axle ya nyuma');
add('FRONT AXLE','前桥','axle ya mbele');
add('REAR AXLE ASSEMBLY','后桥总成','axle ya nyuma kamili');
add('AXLE HOUSING','桥壳','nyumba ya axle');
add('AXLE BOOT','半轴防尘套','boot ya axle');
add('DIFFERENTIAL','差速器','difu');
add('DIFFERENTIAL ASSEMBLY','差速器总成','difu kamili');
add('DIFFERENTIAL BEARING','差速器轴承','bearing ya difu');
add('DIFFERENTIAL SEAL','差速器油封','seal ya difu');
add('DIFFERENTIAL GASKET','差速器垫片','gasketi ya difu');
add('DIFFERENTIAL COVER','差速器盖','kifuniko cha difu');
add('DIFFERENTIAL COVER GASKET','差速器盖垫片','gasketi ya kifuniko cha difu');
add('DIFFERENTIAL PINION','差速器行星齿轮','pinion ya difu');
add('DIFFERENTIAL RING GEAR','差速器盆齿','ring gear ya difu');
add('DIFFERENTIAL SIDE GEAR','差速器半轴齿轮','side gear ya difu');
add('DIFFERENTIAL CARRIER','差速器壳体','carrier ya difu');
add('PINION SEAL','小齿轮油封','seal ya pinion');
add('PINION BEARING','小齿轮轴承','bearing ya pinion');
add('PINION GEAR','小齿轮','giya ya pinion');
add('RING GEAR','盆齿','ring gear');
add('RING AND PINION','盆角齿','ring na pinion');
add('LIMITED SLIP DIFFERENTIAL','限滑差速器','LSD');
add('LOCKING DIFFERENTIAL','锁止差速器','difu ya kufunga');
add('LOCKER DIFFERENTIAL','差速锁','locker ya difu');
add('DIFFERENTIAL LOCK','差速锁','lock ya difu');
add('FOUR WHEEL DRIVE','四驱','4WD');
add('ALL WHEEL DRIVE','全轮驱动','AWD');
add('FRONT WHEEL DRIVE','前驱','FWD');
add('REAR WHEEL DRIVE','后驱','RWD');
add('TWO WHEEL DRIVE','两驱','2WD');
add('WHEEL HUB','轮毂','hub');
add('WHEEL HUB ASSEMBLY','轮毂总成','hub kamili');
add('WHEEL HUB BEARING','轮毂轴承','bearing ya hub');
add('WHEEL HUB UNIT','轮毂轴承单元','kitengo cha hub');
add('HUB BEARING','轮毂轴承','bearing ya hub');
add('FRONT HUB','前轮毂','hub ya mbele');
add('REAR HUB','后轮毂','hub ya nyuma');
add('HUB ASSEMBLY','轮毂总成','hub kamili');
add('HUB SEAL','轮毂油封','seal ya hub');
add('HUB CAP','轮毂盖','kifuniko cha hub');
add('WHEEL STUD','轮胎螺丝柱','stud ya gurudumu');
add('WHEEL NUT','轮胎螺母','nati ya gurudumu');
add('LUG NUT','轮胎螺母','nati ya gurudumu');
add('WHEEL BOLT','轮胎螺丝','bolti ya gurudumu');
add('WHEEL SPACER','法兰盘','spacer ya gurudumu');
add('WHEEL ADAPTER','轮毂适配器','adapter ya gurudumu');

// ═══════════════════════════════════════════════════════════
// BRAKE SYSTEM — 刹车系统 — MFUMO WA BREKI
// ═══════════════════════════════════════════════════════════
add('BRAKE SYSTEM','刹车系统','mfumo wa breki');
add('BRAKE','刹车','breki');
add('BRAKE PEDAL','刹车踏板','pedali ya breki');
add('BRAKE SWITCH','刹车开关','switchi ya breki');
add('BRAKE LIGHT SWITCH','刹车灯开关','switchi ya taa za breki');
add('BRAKE FLUID','刹车油','mafuta ya breki');
add('BRAKE FLUID DOT3','刹车油DOT3','mafuta ya breki DOT3');
add('BRAKE FLUID DOT4','刹车油DOT4','mafuta ya breki DOT4');
add('BRAKE FLUID DOT5','刹车油DOT5','mafuta ya breki DOT5');
add('BRAKE FLUID DOT5.1','刹车油DOT5.1','mafuta ya breki DOT5.1');
add('BRAKE FLUID RESERVOIR','刹车油壶','chombo cha mafuta ya breki');
add('BRAKE RESERVOIR','刹车油壶','chombo cha breki');
add('BRAKE MASTER CYLINDER','刹车总泵','master cylinder ya breki');
add('BRAKE MASTER CYLINDER REPAIR KIT','刹车总泵维修包','seti ya master cylinder');
add('BRAKE BOOSTER','刹车助力器','boosta ya breki');
add('BRAKE VACUUM BOOSTER','刹车真空助力器','boosta ya vacuum');
add('BRAKE BOOSTER HOSE','刹车助力器真空管','hose ya boosta');
add('BRAKE BOOST VACUUM TUBE','刹车助力真空管','tube ya vacuum ya boosta');
add('BRAKE WHEEL CYLINDER','刹车分泵','wheel cylinder');
add('BRAKE CYLINDER','刹车分泵','cylinder ya breki');
add('WHEEL CYLINDER','刹车分泵','wheel cylinder');
add('WHEEL CYLINDER REPAIR KIT','刹车分泵维修包','seti ya wheel cylinder');
add('BRAKE CALIPER','刹车分泵','caliper ya breki');
add('BRAKE CALIPER FRONT','前刹车分泵','caliper ya mbele');
add('BRAKE CALIPER REAR','后刹车分泵','caliper ya nyuma');
add('BRAKE CALIPER REPAIR KIT','刹车分泵维修包','seti ya caliper');
add('BRAKE CALIPER SEAL','刹车分泵密封圈','seal ya caliper');
add('BRAKE CALIPER BOOT','刹车分泵防尘套','boot ya caliper');
add('BRAKE CALIPER GUIDE PIN','刹车分泵导向销','pini ya caliper');
add('BRAKE CALIPER BOLT','刹车分泵螺丝','bolti ya caliper');
add('BRAKE CALIPER BRACKET','刹车分泵支架','bracket ya caliper');
add('BRAKE CALIPER PISTON','刹车分泵活塞','pistoni ya caliper');
add('DISC BRAKE','盘式刹车','breki ya disc');
add('BRAKE DISC','刹车盘','disc ya breki');
add('BRAKE ROTOR','刹车盘','rota ya breki');
add('BRAKE DISC FRONT','前刹车盘','disc ya mbele');
add('BRAKE DISC REAR','后刹车盘','disc ya nyuma');
add('BRAKE DISC SET','刹车盘套件','seti ya disc ya breki');
add('DRUM BRAKE','鼓式刹车','breki ya drum');
add('BRAKE DRUM','刹车鼓','drum ya breki');
add('BRAKE DRUM REAR','后刹车鼓','drum ya nyuma');
add('BRAKE SHOE','刹车蹄','kiatu cha breki');
add('BRAKE LINING SHOE','刹车蹄片','kiatu cha breki chenye lining');
add('BRAKE SHOE REAR','后刹车蹄','kiatu cha breki ya nyuma');
add('BRAKE SHOE SET','刹车蹄组','seti ya kiatu cha breki');
add('BRAKE PAD','刹车片','padi ya breki');
add('BRAKE PAD FRONT','前刹车片','padi ya breki ya mbele');
add('BRAKE PAD REAR','后刹车片','padi ya breki ya nyuma');
add('BRAKE PAD SET','刹车片套件','seti ya padi ya breki');
add('BRAKE PAD WEAR SENSOR','刹车片磨损传感器','sensa ya uchakavu wa padi');
add('BRAKE PAD SHIM','刹车片消音片','shim ya padi ya breki');
add('BRAKE PAD CLIP','刹车片卡簧','clip ya padi ya breki');
add('BRAKE HOSE','刹车软管','hose ya breki');
add('BRAKE HOSE FRONT','前刹车软管','hose ya breki ya mbele');
add('BRAKE HOSE REAR','后刹车软管','hose ya breki ya nyuma');
add('BRAKE PIPE','刹车硬管','pipe ya breki');
add('BRAKE LINE','刹车油管','laini ya breki');
add('BRAKE TUBE','刹车管','tube ya breki');
add('BRAKE PROPORTIONING VALVE','刹车比例阀','valvu ya kugawa');
add('PROPORTIONAL VALVE','比例阀','proportional valve');
add('BRAKE RESIDUAL VALVE','刹车残余阀','valvu ya mabaki');
add('LOAD SENSING VALVE','感载阀','valvu ya kuhisi mzigo');
add('BRAKE CHECK VALVE','刹车单向阀','valvu ya kukagua');
add('HAND BRAKE','手刹','hand brake');
add('PARKING BRAKE','驻车制动','breki ya kuegesha');
add('PARKING BRAKE CABLE','手刹拉线','kebo ya hand brake');
add('HAND BRAKE CABLE','手刹拉线','kebo ya hand brake');
add('PARKING BRAKE LEVER','手刹拉杆','lever ya hand brake');
add('PARKING BRAKE SHOE','手刹刹车蹄','kiatu cha hand brake');
add('PARKING BRAKE PAD','手刹刹车片','padi ya hand brake');
add('HAND BRAKE HANDLE','手刹把手','mkono wa hand brake');
add('HAND BRAKE SWITCH','手刹开关','switchi ya hand brake');
add('ABS','防抱死刹车系统','ABS');
add('ABS MODULE','ABS模块','moduli ya ABS');
add('ABS PUMP','ABS泵','pampu ya ABS');
add('ABS CONTROL MODULE','ABS控制模块','moduli ya kudhibiti ABS');
add('ABS RELAY','ABS继电器','relay ya ABS');
add('ABS RING','ABS感应齿圈','pete ya ABS');
add('ABS TONE RING','ABS齿圈','tone ring ya ABS');
add('ABS HARNESS','ABS线束','waya za ABS');
add('BRAKE BLEEDING','刹车排气','kutoa hewa breki');
add('BRAKE FLUSH','刹车油更换','kubadilisha mafuta ya breki');
add('BRAKE ADJUSTMENT','刹车调整','kurekebisha breki');
add('BRAKE REPAIR','刹车维修','kutengeneza breki');
add('BRAKE NOISE','刹车异响','breki kelele');
add('BRAKE SQUEAK','刹车尖叫','breki kulia');
add('BRAKE VIBRATION','刹车抖动','breki kutetemeka');

// ═══════════════════════════════════════════════════════════
// SUSPENSION — 悬挂 — Mfumo wa Kusimamisha
// ═══════════════════════════════════════════════════════════
add('SUSPENSION','悬挂','mifumo ya kusimamisha');
add('SUSPENSION SYSTEM','悬挂系统','mfumo wa kusimamisha');
add('SUSPENSION BUSHING','悬挂胶套','bushi ya suspension');
add('SUSPENSION ARM','悬挂臂','mkono wa suspension');
add('SUSPENSION SPRING','悬挂弹簧','springi ya suspension');
add('SPRING','弹簧','springi');
add('COIL SPRING','螺旋弹簧','springi ya coil');
add('COIL SPRING FRONT','前弹簧','springi ya mbele');
add('COIL SPRING REAR','后弹簧','springi ya nyuma');
add('LEAF SPRING','钢板弹簧','springi ya chuma');
add('LEAF SPRING BUSH','钢板弹簧胶套','bushi ya leaf spring');
add('LEAF SPRING BOLT','钢板弹簧螺丝','bolti ya leaf spring');
add('LEAF SPRING SHACKLE','钢板弹簧吊耳','shackle ya leaf spring');
add('LEAF SPRING CENTER BOLT','钢板中心螺丝','bolti ya kati');
add('LEAF SPRING U-BOLT','钢板U型螺栓','U-bolti');
add('TORSION BAR','扭力杆','torsion bar');
add('TORSION BAR BUSH','扭力杆胶套','bushi ya torsion bar');
add('AIR SPRING','空气弹簧','springi ya hewa');
add('AIR BAG','气囊','air bag');
add('AIR SUSPENSION','空气悬挂','suspension ya hewa');
add('AIR STRUT','空气减震','strut ya hewa');
add('AIR COMPRESSOR SUSPENSION','悬挂气泵','compressor ya suspension');
add('SHOCK ABSORBER','减震器','shock absorber');
add('SHOCK ABSORBER FRONT','前减震器','shock ya mbele');
add('SHOCK ABSORBER REAR','后减震器','shock ya nyuma');
add('STRUT','减震器总成','strut');
add('STRUT ASSEMBLY','减震器总成','strut kamili');
add('STRUT MOUNT','减震器顶胶','mount ya strut');
add('SHOCK MOUNTING','减震器顶胶','mount ya shock');
add('STRUT MOUNT BEARING','塔顶轴承','bearing ya mount ya strut');
add('STRUT BOOT','减震器防尘套','boot ya strut');
add('STRUT BUMPER','减震器缓冲块','bumper ya strut');
add('STRUT BELLOWS','减震器防尘套','bellows ya strut');
add('SHOCK BUSHING','减震器胶套','bushi ya shock');
add('SWAY BAR','平衡杆','sway bar');
add('STABILIZER BAR','平衡杆','stabilizer bar');
add('STABILIZER BUSH','平衡杆胶套','bushi ya stabilizer');
add('STABILIZER LINK','平衡杆小连杆','linki ya stabilizer');
add('SWAY BAR LINK','平衡杆连杆','linki ya sway bar');
add('STABILIZER BAR LINK','平衡杆连杆','linki ya stabilizer bar');
add('SWAY BAR BUSH','平衡杆胶套','bushi ya sway bar');
add('CONTROL ARM','控制臂','control arm');
add('LOWER ARM','下摆臂','lower arm');
add('LOWER CONTROL ARM','下控制臂','lower control arm');
add('UPPER ARM','上摆臂','upper arm');
add('UPPER CONTROL ARM','上控制臂','upper control arm');
add('CONTROL ARM BUSH','控制臂胶套','bushi ya control arm');
add('LOWER ARM BUSH','下摆臂胶套','bushi ya lower arm');
add('UPPER ARM BUSH','上摆臂胶套','bushi ya upper arm');
add('WISHBONE','三角臂','wishbone');
add('WISHBONE BUSH','三角臂胶套','bushi ya wishbone');
add('TRAILING ARM','纵臂','trailing arm');
add('TRAILING ARM BUSH','纵臂胶套','bushi ya trailing arm');
add('RADIUS ARM','半径臂','radius arm');
add('RADIUS ARM BUSH','半径臂胶套','bushi ya radius arm');
add('PANHARD ROD','止推杆','panhard rod');
add('PANHARD ROD BUSH','止推杆胶套','bushi ya panhard rod');
add('CROSS MEMBER','横梁','cross member');
add('CROSS MEMBER BUSH','横梁胶套','bushi ya cross member');
add('SUBFRAME','副车架','subframe');
add('SUBFRAME BUSH','副车架胶套','bushi ya subframe');
add('ENGINE CRADLE','发动机托架','cradle ya injini');
add('BALL JOINT','球头','ball joint');
add('BALL JOINT FRONT','前球头','ball joint ya mbele');
add('BALL JOINT REAR','后球头','ball joint ya nyuma');
add('LOWER BALL JOINT','下球头','ball joint ya chini');
add('UPPER BALL JOINT','上球头','ball joint ya juu');
add('BALL JOINT BOOT','球头防尘套','boot ya ball joint');
add('BALL JOINT PRESS','压球头工具','chombo cha kubana ball joint');
add('SPINDLE','转向节','spindle');
add('KNUCKLE','转向节','knuckle');
add('STEERING KNUCKLE','转向节','steering knuckle');
add('KNUCKLE ARM','转向节臂','mkono wa knuckle');
add('WHEEL ALIGNMENT','四轮定位','upangaji wa magurudumu');
add('WHEEL BALANCE','轮胎平衡','kusawazisha magurudumu');
add('CAMBER','外倾角','camber');
add('CASTER','主销后倾','caster');
add('TOE','前束','toe');
add('ALIGNMENT SHIM','定位垫片','shim ya alignment');

// ═══════════════════════════════════════════════════════════
// STEERING — 转向系统 — USUKANI
// ═══════════════════════════════════════════════════════════
add('STEERING SYSTEM','转向系统','mfumo wa usukani');
add('STEERING','转向','usukani');
add('STEERING WHEEL','方向盘','steering wheel');
add('STEERING COLUMN','方向管柱','column ya usukani');
add('STEERING COLUMN COVER','方向管柱罩','kifuniko cha column');
add('STEERING COLUMN BEARING','方向管柱轴承','bearing ya column');
add('STEERING COLUMN SWITCH','组合开关','switchi ya column');
add('STEERING SHAFT','转向轴','shafti ya usukani');
add('STEERING COUPLING','转向联轴器','coupling ya usukani');
add('STEERING RACK','方向机','steering rack');
add('STEERING GEAR','方向机','giya ya usukani');
add('STEERING BOX','方向机','steering box');
add('STEERING GEAR BOX','方向机总成','steering gear box');
add('RACK AND PINION','齿轮齿条方向机','rack na pinion');
add('POWER STEERING','助力转向','power steering');
add('POWER STEERING PUMP','助力泵','pampu ya power steering');
add('POWER STEERING PUMP PULLEY','助力泵皮带轮','pulley ya pampu ya usukani');
add('POWER STEERING HOSE','助力泵高压管','hose ya power steering');
add('POWER STEERING HIGH PRESSURE HOSE','助力泵高压管','hose ya shinikizo la juu');
add('POWER STEERING RETURN HOSE','助力泵回油管','hose ya kurudi');
add('POWER STEERING PIPE','助力泵油管','pipe ya power steering');
add('POWER STEERING COOLER','助力油冷却器','kipozaji cha power steering');
add('POWER STEERING FLUID','方向机油','mafuta ya power steering');
add('POWER STEERING OIL','助力泵油','mafuta ya usukani');
add('POWER STEERING RESERVOIR','助力油壶','chombo cha power steering');
add('POWER STEERING CAP','助力油盖','kifuniko cha power steering');
add('STEERING LINKAGE','转向连杆','linkage ya usukani');
add('TIE ROD','方向机拉杆','tie rod');
add('TIE ROD END','方向机拉杆球头','ncha ya tie rod');
add('INNER TIE ROD','方向机内拉杆','tie rod ya ndani');
add('OUTER TIE ROD','方向机外拉杆','tie rod ya nje');
add('RACK END','方向机拉杆球头','rack end');
add('TIE ROD BOOT','方向机防尘套','boot ya tie rod');
add('TIE ROD ADJUSTER','方向机拉杆调节器','adjuster ya tie rod');
add('DRAG LINK','直拉杆','drag link');
add('PITMAN ARM','转向摇臂','pitman arm');
add('IDLER ARM','转向随动臂','idler arm');
add('DROP ARM','转向垂臂','drop arm');
add('KING PIN','主销','king pin');
add('KING PIN KIT','主销套装','seti ya king pin');
add('KING PIN BEARING','主销轴承','bearing ya king pin');
add('KING PIN BUSH','主销胶套','bushi ya king pin');
add('STEERING DAMPER','方向减震器','damper ya usukani');
add('STEERING STABILIZER','方向稳定器','stabilizer ya usukani');

// ═══════════════════════════════════════════════════════════
// WHEELS / TIRES — 车轮/轮胎 — MAGURUDUMU / MATAIRI
// ═══════════════════════════════════════════════════════════
add('WHEEL','车轮','gurudumu');
add('TIRE','轮胎','tairi');
add('TYRE','轮胎','tairi');
add('TIRE PRESSURE','轮胎气压','shinikizo la tairi');
add('TIRE VALVE','气门嘴','valvu ya tairi');
add('TIRE VALVE CAP','气门嘴帽','kifuniko cha valvu ya tairi');
add('TIRE VALVE STEM','气门芯','kijiti cha valvu');
add('TIRE VALVE CORE','气门芯','kini cha valvu');
add('TIRE PUNCTURE','轮胎扎破','tairi kutoboka');
add('TIRE REPAIR','补胎','kutengeneza tairi');
add('TIRE PLUG','轮胎补胎条','plagi ya tairi');
add('TIRE PATCH','轮胎补片','kiraka cha tairi');
add('TIRE PRESSURE SENSOR','胎压传感器','TPMS');
add('TIRE PRESSURE MONITOR','胎压监测','kifuatilia shinikizo la tairi');
add('TIRE BALANCE','轮胎动平衡','kusawazisha tairi');
add('TIRE ROTATION','轮胎换位','kuzungusha matairi');
add('TIRE WEAR','轮胎磨损','uchakavu wa tairi');
add('TIRE TREAD','轮胎花纹','kukanyaga tairi');
add('SPARE TIRE','备胎','tairi ya spare');
add('SPARE WHEEL','备胎','gurudumu la spare');
add('TIRE IRON','轮胎撬棍','mtalimbo wa tairi');
add('WHEEL WEIGHT','平衡块','uzito wa gurudumu');
add('WHEEL BALANCE WEIGHT','轮胎平衡块','uzito wa kusawazisha');
add('TIRE GAUGE','胎压表','geji ya tairi');
add('TIRE INFLATOR','轮胎充气泵','pampu ya kujaza tairi');
add('TIRE CHANGER','拆胎机','mashine ya kubadilisha tairi');
add('WHEEL ALIGNMENT MACHINE','四轮定位仪','mashine ya alignment');
add('WHEEL BALANCER','轮胎平衡机','mashine ya kusawazisha');
add('TIRE SHINE','轮胎上光剂','dawa ya kung\'arisha tairi');
add('TIRE CLEANER','轮胎清洗剂','dawa ya kusafisha tairi');
add('WHEEL CLEANER','轮毂清洗剂','dawa ya kusafisha gurudumu');
add('WHEEL LOCK','防盗螺丝','kufuli ya gurudumu');
add('WHEEL COVER','轮毂盖','kifuniko cha gurudumu');
add('WHEEL RIM','轮辋','rimu');
add('ALLOY WHEEL','铝合金轮毂','gurudumu la alloy');
add('STEEL WHEEL','钢轮毂','gurudumu la chuma');
add('INNER TUBE','内胎','mrija wa ndani');
add('FLAP','衬带','flap');

// ═══════════════════════════════════════════════════════════
// AIR CONDITIONING — 空调系统 — KIYOYO
// ═══════════════════════════════════════════════════════════
add('AC SYSTEM','空调系统','mfumo wa AC');
add('AIR CONDITIONING','空调','kiyoyo');
add('AC COMPRESSOR','空调压缩机','compressor ya AC');
add('COMPRESSOR','压缩机','compressor');
add('AC COMPRESSOR CLUTCH','空调压缩机离合器','clutch ya compressor');
add('AC COMPRESSOR OIL','压缩机油','mafuta ya compressor');
add('COMPRESSOR OIL','压缩机油','mafuta ya compressor');
add('AC COMPRESSOR SEAL','压缩机密封圈','seal ya compressor');
add('AC COMPRESSOR BEARING','压缩机轴承','bearing ya compressor');
add('AC COMPRESSOR PULLEY','压缩机皮带轮','pulley ya compressor');
add('AC COMPRESSOR BRACKET','压缩机支架','bracket ya compressor');
add('AC COMPRESSOR RELAY','压缩机继电器','relay ya compressor');
add('AC CONDENSER','空调冷凝器','condenser ya AC');
add('CONDENSER','冷凝器','condenser');
add('AC CONDENSER FAN','冷凝器风扇','feni ya condenser');
add('CONDENSER FAN','冷凝器风扇','feni ya condenser');
add('AC EVAPORATOR','空调蒸发器','evaporator ya AC');
add('EVAPORATOR','蒸发器','evaporator');
add('AC EVAPORATOR COIL','蒸发器芯','coil ya evaporator');
add('AC DRIER','空调干燥瓶','dryer ya AC');
add('RECEIVER DRIER','干燥瓶','receiver dryer');
add('AC RECEIVER','空调储液罐','receiver ya AC');
add('AC FILTER','空调过滤器','chujio la AC');
add('CABIN FILTER','空调滤清器','chujio la cabin');
add('CABIN AIR FILTER','空调滤芯','chujio la hewa ya cabin');
add('POLLEN FILTER','花粉过滤器','chujio la poleni');
add('AC EXPANSION VALVE','空调膨胀阀','expansion valve');
add('EXPANSION VALVE','膨胀阀','expansion valve');
add('AC PIPE','空调管','pipe ya AC');
add('AC HOSE','空调软管','hose ya AC');
add('AC HOSE HIGH PRESSURE','空调高压管','hose ya shinikizo la juu');
add('AC HOSE LOW PRESSURE','空调低压管','hose ya shinikizo la chini');
add('AC DUCT','空调风道','duct ya AC');
add('AC VENT','空调出风口','vent ya AC');
add('AC GAS','空调冷媒','gesi ya AC');
add('AC REFRIGERANT','空调制冷剂','refrigerant ya AC');
add('R134A','R134a制冷剂','R134a');
add('R1234YF','R1234yf制冷剂','R1234yf');
add('AC RECHARGE','空调加氟','kujaza AC');
add('AC SERVICE','空调保养','service ya AC');
add('AC REPAIR','空调维修','kutengeneza AC');
add('AC LEAK','空调泄漏','kuvuja AC');
add('AC LEAK DETECTOR','空调检漏仪','kifaa cha kugundua kuvuja');
add('AC PRESSURE SWITCH','空调压力开关','switchi ya shinikizo la AC');
add('AC PRESSURE SENSOR','空调压力传感器','sensa ya shinikizo la AC');
add('AC HIGH PRESSURE SWITCH','空调高压开关','switchi ya shinikizo la juu');
add('AC LOW PRESSURE SWITCH','空调低压开关','switchi ya shinikizo la chini');
add('AC CONTROL PANEL','空调控制面板','paneli ya kudhibiti AC');
add('AC CONTROL MODULE','空调控制模块','moduli ya kudhibiti AC');
add('AC BLOWER','空调鼓风机','blower ya AC');
add('BLOWER MOTOR','鼓风机马达','mota ya blower');
add('BLOWER RESISTOR','鼓风机电阻','resistor ya blower');
add('BLOWER SWITCH','鼓风机开关','switchi ya blower');
add('HEATER','暖风','heater');
add('HEATER CORE','暖风水箱','kini ya heater');
add('HEATER ASSEMBLY','暖风总成','heater kamili');
add('HEATER HOSE','暖风水管','hose ya heater');
add('HEATER VALVE','暖风阀','valvu ya heater');
add('HEATER CONTROL','暖风控制','udhibiti wa heater');
add('HEATER RESISTOR','暖风电阻','resistor ya heater');
add('HEATER FAN','暖风风扇','feni ya heater');
add('HEATER BLOWER','暖风鼓风机','blower ya heater');
add('CLIMATE CONTROL','自动空调','climate control');
add('AUTO AC','自动空调','AC otomatiki');
add('DUAL ZONE AC','双区空调','AC sehemu mbili');
add('AC THERMOSTAT','空调温控器','thermostat ya AC');
add('AC AMBIENT TEMPERATURE SENSOR','环境温度传感器','sensa ya joto la nje');
add('AC EVAPORATOR TEMPERATURE SENSOR','蒸发器温度传感器','sensa ya joto la evaporator');
add('AC ACTUATOR','空调执行器','actuator ya AC');
add('AIR DISTRIBUTION','空气分配','usambazaji wa hewa');
add('AIR PURIFIER','空气净化器','kisafisha hewa');
add('AC INSULATION','空调保温棉','insulation ya AC');

// ═══════════════════════════════════════════════════════════
// EXHAUST / EMISSIONS — 排气/排放 — MFUMO WA EXHAUST
// ═══════════════════════════════════════════════════════════
add('OXYGEN SENSOR UPSTREAM','前氧传感器','sensa ya O2 ya mbele');
add('OXYGEN SENSOR DOWNSTREAM','后氧传感器','sensa ya O2 ya nyuma');
add('AIR FUEL RATIO SENSOR','空燃比传感器','sensa ya AFR');
add('EXHAUST GAS RECIRCULATION','废气再循环','EGR');
add('EVAP SYSTEM','燃油蒸发系统','mfumo wa EVAP');
add('EVAP CANISTER','碳罐','canister ya EVAP');
add('EVAP PURGE VALVE','碳罐电磁阀','valvu ya purge');
add('EVAP VENT VALVE','碳罐通风阀','valvu ya vent');
add('EVAP SOLENOID','蒸发电磁阀','solenoidi ya EVAP');
add('EVAP HOSE','燃油蒸发管','hose ya EVAP');
add('CHARCOAL CANISTER','活性碳罐','canister ya mkaa');
add('SECONDARY AIR PUMP','二次空气泵','pampu ya hewa ya pili');
add('SECONDARY AIR VALVE','二次空气阀','valvu ya hewa ya pili');
add('FUEL VAPOR VALVE','燃油蒸汽阀','valvu ya mvuke ya mafuta');
add('EMISSION CONTROL','排放控制','udhibiti wa uzalishaji');
add('SMOG PUMP','排气泵','pampu ya smog');

// ═══════════════════════════════════════════════════════════
// ELECTRICAL / ELECTRONICS — 电器 — UMEME / ELECTRONICS
// ═══════════════════════════════════════════════════════════
add('ALTERNATOR BRUSH SET','发电机碳刷组','seti ya brashi ya alterneta');
add('STARTER BRUSH SET','启动机碳刷组','seti ya brashi ya starter');
add('VOLTAGE REGULATOR','电压调节器','regulator ya voltage');
add('RECTIFIER','整流器','rectifier');
add('DIODE','二极管','diode');
add('DIODE PACK','二极管组','pack ya diode');
add('FUSE','保险丝','fuse');
add('FUSE BOX','保险丝盒','sanduku la fuse');
add('FUSE BOX COVER','保险丝盒盖','kifuniko cha sanduku la fuse');
add('FUSE HOLDER','保险丝座','kishikizi cha fuse');
add('FUSE PULLER','保险丝拔取器','kivuta fuse');
add('FUSE KIT','保险丝套装','seti ya fuse');
add('BLADE FUSE','片式保险丝','fuse ya blade');
add('MINI FUSE','迷你保险丝','fuse ndogo');
add('MAXI FUSE','大型保险丝','fuse kubwa');
add('FUSIBLE LINK','保险丝连接线','fusible link');
add('CIRCUIT BREAKER','断路器','breaker');
add('RELAY','继电器','relay');
add('RELAY BOX','继电器盒','sanduku la relay');
add('FUEL PUMP RELAY','燃油泵继电器','relay ya pampu ya mafuta');
add('HORN RELAY','喇叭继电器','relay ya honi');
add('WIPER RELAY','雨刮继电器','relay ya wiper');
add('HEADLIGHT RELAY','大灯继电器','relay ya taa kubwa');
add('FOG LIGHT RELAY','雾灯继电器','relay ya fog light');
add('AC RELAY','空调继电器','relay ya AC');
add('BLOWER RELAY','鼓风机继电器','relay ya blower');
add('FLASHER RELAY','闪光继电器','relay ya flasher');
add('GLOW PLUG RELAY','预热继电器','relay ya glow plug');
add('TURN SIGNAL RELAY','转向灯继电器','relay ya turn signal');
add('STARTER RELAY','启动继电器','relay ya starter');
add('RELAY TESTER','继电器测试仪','kipima relay');
add('WIRING HARNESS','线束','wiring harness');
add('WIRE HARNESS','线束','wire harness');
add('ENGINE WIRING HARNESS','发动机线束','wiring harness ya injini');
add('BODY WIRING HARNESS','车身线束','wiring harness ya body');
add('HEADLIGHT HARNESS','大灯线束','waya za taa');
add('TAILLIGHT HARNESS','尾灯线束','waya za taa za nyuma');
add('WIRE','电线','waya');
add('CABLE','电缆','kebo');
add('WIRE LOOM','线束套管','mfuko wa waya');
add('CABLE TIE','扎带','cable tie');
add('WIRE CONNECTOR','电线接头','connector ya waya');
add('ELECTRICAL CONNECTOR','电器插头','connector ya umeme');
add('CONNECTOR','插头','connector');
add('CONNECTOR CLIP','插头卡扣','clip ya connector');
add('TERMINAL','端子','terminal');
add('WIRE TERMINAL','电线端子','terminal ya waya');
add('BULLET CONNECTOR','子弹头端子','connector ya risasi');
add('SPADE CONNECTOR','扁平端子','connector gorofa');
add('RING TERMINAL','环形端子','terminal ya pete');
add('BUTT CONNECTOR','对接端子','connector ya kukuta');
add('HEAT SHRINK TUBING','热缩管','tube ya kusinyaa');
add('INSULATION TAPE','绝缘胶带','tepu ya insulation');
add('ELECTRICAL TAPE','电工胶带','tepu ya umeme');
add('SOLDER','焊锡','solder');
add('SOLDERING IRON','电烙铁','chuma cha solder');
add('MULTIMETER','万用表','multimeter');
add('CIRCUIT TESTER','电路测试笔','kipima mzunguko');
add('POWER PROBE','电源探针','power probe');
add('BATTERY TESTER','电瓶检测仪','kipima betri');
add('ALTERNATOR TESTER','发电机检测仪','kipima alterneta');
add('OBD SCANNER','OBD诊断仪','scanner ya OBD');
add('DIAGNOSTIC SCANNER','诊断仪','scanner ya kuchunguza');
add('DIAGNOSTIC TOOL','诊断工具','chombo cha kuchunguza');
add('JUMPER CABLE','过江龙','kebo ya kupasha moto');
add('JUMP LEAD','搭电线','waya ya kupasha moto');
add('JUMP START','搭电启动','kupasha moto');
add('BOOSTER CABLE','启动搭电线','kebo ya boost');
add('TOW ROPE','拖车绳','kamba ya kuvuta');
add('TOW STRAP','拖车带','mkanda wa kuvuta');
add('TOW HITCH','拖车钩','ndoano ya kuvuta');
add('RECOVERY STRAP','救援带','mkanda wa uokoaji');
add('WINCH','绞盘','winch');
add('JACK','千斤顶','jack');
add('JACK STAND','千斤顶支架','standi ya jack');
add('HYDRAULIC JACK','液压千斤顶','jack ya hydraulic');
add('SCISSOR JACK','剪式千斤顶','jack ya mkasi');
add('FLOOR JACK','卧式千斤顶','jack ya sakafu');
add('BOTTLE JACK','瓶式千斤顶','jack ya chupa');
add('WHEEL CHOCK','车轮挡块','kizuizi cha gurudumu');
add('WHEEL WRENCH','轮胎扳手','spana ya gurudumu');
add('LUG WRENCH','轮胎套筒','spana ya lug');
add('TORQUE WRENCH','扭力扳手','spana ya torque');
add('IMPACT WRENCH','风炮','spana ya impact');
add('SOCKET SET','套筒组','seti ya socket');
add('SOCKET','套筒','socket');
add('RATCHET','棘轮扳手','ratchet');
add('RATCHET SET','棘轮扳手套装','seti ya ratchet');
add('SPANNER','扳手','spana');
add('COMBINATION SPANNER','梅花扳手','spana ya combination');
add('OPEN SPANNER','开口扳手','spana ya wazi');
add('RING SPANNER','梅花扳手','spana ya pete');
add('ADJUSTABLE SPANNER','活动扳手','spana ya kubadilika');
add('PIPE WRENCH','管钳','spana ya pipe');
add('ALLEN KEY','内六角扳手','ufunguo wa allen');
add('HEX KEY','内六角扳手','ufunguo wa hex');
add('SCREWDRIVER','螺丝刀','screwdriver');
add('FLAT SCREWDRIVER','一字螺丝刀','screwdriver gorofa');
add('PHILLIPS SCREWDRIVER','十字螺丝刀','screwdriver ya msalaba');
add('PLIERS','钳子','pliers');
add('NEEDLE NOSE PLIERS','尖嘴钳','pliers ya pua ndefu');
add('COMBINATION PLIERS','钢丝钳','pliers ya combination');
add('LOCKING PLIERS','大力钳','pliers ya kufunga');
add('CIRCLIP PLIERS','卡环钳','pliers ya circlip');
add('WIRE STRIPPER','剥线钳','kivua waya');
add('WIRE CRIMPER','压线钳','kibana waya');
add('HAMMER','锤子','nyundo');
add('RUBBER MALLET','橡胶锤','nyundo ya mpira');
add('BALL PEEN HAMMER','圆头锤','nyundo ya duara');
add('PUNCH','冲子','punch');
add('CHISEL','凿子','chisel');
add('FILE','锉刀','file');
add('HACKSAW','钢锯','hacksaw');
add('DRILL','电钻','drill');
add('DRILL BIT','钻头','bit ya drill');
add('ANGLE GRINDER','角磨机','angle grinder');
add('BENCH GRINDER','砂轮机','bench grinder');
add('IMPACT DRIVER','冲击螺丝刀','impact driver');
add('AIR COMPRESSOR','空气压缩机','compressor ya hewa');
add('AIR HOSE','气动软管','hose ya hewa');
add('AIR TOOL','气动工具','chombo cha hewa');
add('GREASE GUN','黄油枪','bunduki ya grisi');
add('OIL CAN','机油壶','chombo cha mafuta');
add('FUNNEL','漏斗','funnel');
add('DRAIN PAN','接油盘','pani ya kukusanya mafuta');
add('PARTS WASHER','零件清洗机','mashine ya kusafisha vipuri');
add('WORKSHOP MANUAL','维修手册','kitabu cha workshop');
add('WORK LIGHT','工作灯','taa ya kazi');
add('DROPLIGHT','吊灯','droplight');
add('HEADLAMP WORK LIGHT','头灯','taa ya kichwa');
add('CREEPER','躺板','creeper');
add('MECHANIC SEAT','修车凳','kiti cha mechanic');
add('TOOL BOX','工具箱','sanduku la zana');
add('TOOL CHEST','工具柜','kasha la zana');
add('TOOL TROLLEY','工具推车','toroli ya zana');
add('GLOVES','手套','glavu');
add('WORK GLOVES','工作手套','glavu za kazi');
add('RUBBER GLOVES','橡胶手套','glavu za mpira');
add('SAFETY GOGGLES','护目镜','miwani ya usalama');
add('SAFETY GLASSES','安全眼镜','miwani ya usalama');
add('FACE MASK','口罩','barakoa');
add('EAR PLUG','耳塞','plagi ya sikio');

// ═══════════════════════════════════════════════════════════
// LIGHTING — 灯光 — TAA
// ═══════════════════════════════════════════════════════════
add('HEADLIGHT','大灯','taa kubwa');
add('HEADLIGHT ASSEMBLY','大灯总成','taa kubwa kamili');
add('HEADLIGHT BULB','大灯灯泡','bulb ya taa kubwa');
add('HEADLIGHT LENS','大灯面罩','lens ya taa kubwa');
add('HEADLIGHT SWITCH','大灯开关','switchi ya taa kubwa');
add('HEADLIGHT RELAY','大灯继电器','relay ya taa kubwa');
add('HEADLIGHT SOCKET','大灯插座','socket ya taa kubwa');
add('HEADLIGHT CONNECTOR','大灯插头','connector ya taa kubwa');
add('HEADLIGHT ADJUSTER','大灯调节器','adjuster ya taa kubwa');
add('HEADLIGHT BRACKET','大灯支架','bracket ya taa kubwa');
add('H4 BULB','H4灯泡','bulb H4');
add('H1 BULB','H1灯泡','bulb H1');
add('H7 BULB','H7灯泡','bulb H7');
add('H11 BULB','H11灯泡','bulb H11');
add('HID BULB','氙气灯泡','bulb HID');
add('HID KIT','氙气灯套装','seti ya HID');
add('HID BALLAST','氙气灯镇流器','ballast ya HID');
add('LED HEADLIGHT','LED大灯','taa kubwa ya LED');
add('LED BULB','LED灯泡','bulb ya LED');
add('LED KIT','LED套装','seti ya LED');
add('XENON BULB','氙气灯泡','bulb ya xenon');
add('FOG LIGHT','雾灯','fog light');
add('FOG LIGHT BULB','雾灯灯泡','bulb ya fog light');
add('FOG LIGHT COVER','雾灯罩','kifuniko cha fog light');
add('FOG LIGHT BRACKET','雾灯支架','bracket ya fog light');
add('TAILLIGHT','尾灯','taa ya nyuma');
add('TAIL LIGHT','尾灯','taa ya nyuma');
add('TAILLIGHT BULB','尾灯灯泡','bulb ya taa ya nyuma');
add('TAILLIGHT ASSEMBLY','尾灯总成','taa ya nyuma kamili');
add('BRAKE LIGHT','刹车灯','taa ya breki');
add('BRAKE LIGHT BULB','刹车灯灯泡','bulb ya taa ya breki');
add('REVERSE LIGHT','倒车灯','taa ya nyuma');
add('REVERSE LIGHT BULB','倒车灯灯泡','bulb ya taa ya nyuma');
add('TURN SIGNAL','转向灯','turn signal');
add('TURN SIGNAL BULB','转向灯灯泡','bulb ya turn signal');
add('TURN SIGNAL SWITCH','转向灯开关','switchi ya turn signal');
add('TURN SIGNAL RELAY','转向灯继电器','relay ya turn signal');
add('SIDE MARKER','侧灯','side marker');
add('SIDE MARKER BULB','侧灯灯泡','bulb ya side marker');
add('PARKING LIGHT','示宽灯','taa ya kuegesha');
add('DAYTIME RUNNING LIGHT','日行灯','DRL');
add('DRL LIGHT','日间行车灯','taa ya DRL');
add('LICENSE PLATE LIGHT','牌照灯','taa ya namba');
add('INTERIOR LIGHT','室内灯','taa ya ndani');
add('DOME LIGHT','顶灯','taa ya dari');
add('MAP LIGHT','阅读灯','taa ya kusomea');
add('VANITY LIGHT','化妆镜灯','taa ya kioo');
add('DOOR LIGHT','门灯','taa ya mlango');
add('COURTESY LIGHT','迎宾灯','taa ya heshima');
add('TRUNK LIGHT','后备箱灯','taa ya buti');
add('GLOVE BOX LIGHT','手套箱灯','taa ya glove box');
add('AMBENT LIGHT','氛围灯','taa ya mazingira');
add('LIGHT BULB','灯泡','bulb ya taa');
add('BULB','灯泡','bulb');
add('HALOGEN BULB','卤素灯泡','bulb ya halogen');
add('LED BULB WHITE','白光LED灯泡','bulb ya LED nyeupe');
add('LED BULB YELLOW','黄光LED灯泡','bulb ya LED manjano');
add('HEADLIGHT POLISH','大灯翻新','kung\'arisha taa');
add('HEADLIGHT RESTORATION','大灯修复','kurejesha taa');

// ═══════════════════════════════════════════════════════════
// BODY / EXTERIOR — 车身/外饰 — MWILI / NJE
// ═══════════════════════════════════════════════════════════
add('BODY','车身','mwili');
add('CAR BODY','车身','mwili wa gari');
add('CHASSIS','底盘','chassis');
add('FRAME','车架','fremu');
add('BODY PANEL','车身面板','paneli ya mwili');
add('FENDER','翼子板','fender');
add('FRONT FENDER','前翼子板','fender ya mbele');
add('REAR FENDER','后翼子板','fender ya nyuma');
add('FENDER LINER','翼子板内衬','mjengo wa fender');
add('HOOD','引擎盖','hood');
add('BONNET','引擎盖','boneti');
add('HOOD HINGE','引擎盖铰链','hinge ya hood');
add('HOOD LATCH','引擎盖锁扣','latch ya hood');
add('HOOD STRUT','引擎盖撑杆','strut ya hood');
add('HOOD INSULATION','引擎盖隔热棉','insulation ya hood');
add('TRUNK','后备箱','buti');
add('BOOT','后备箱','buti');
add('TRUNK LID','后备箱盖','kifuniko cha buti');
add('TRUNK HINGE','后备箱铰链','hinge ya buti');
add('TRUNK STRUT','后备箱撑杆','strut ya buti');
add('TRUNK LOCK','后备箱锁','kufuli ya buti');
add('DOOR','车门','mlango');
add('FRONT DOOR','前门','mlango wa mbele');
add('REAR DOOR','后门','mlango wa nyuma');
add('SLIDING DOOR','滑门','mlango wa kuteleza');
add('DOOR PANEL','门板','paneli ya mlango');
add('DOOR HANDLE','门把手','kipini cha mlango');
add('DOOR HANDLE OUTER','外门把手','kipini cha nje');
add('DOOR HANDLE INNER','内门把手','kipini cha ndani');
add('DOOR LOCK','门锁','kufuli ya mlango');
add('DOOR LOCK ACTUATOR','门锁电机','actuator ya kufuli');
add('DOOR LATCH','门锁扣','latch ya mlango');
add('DOOR HINGE','车门铰链','hinge ya mlango');
add('DOOR CHECK','车门限位器','check ya mlango');
add('DOOR SEAL','车门密封条','seal ya mlango');
add('DOOR WEATHERSTRIP','车门防水条','weatherstrip ya mlango');
add('WEATHERSTRIP','密封条','weatherstrip');
add('WINDOW','车窗','dirisha');
add('WINDOW GLASS','车窗玻璃','kioo cha dirisha');
add('DOOR GLASS','车门玻璃','kioo cha mlango');
add('QUARTER GLASS','三角窗玻璃','kioo cha pembetatu');
add('WINDOW REGULATOR','玻璃升降器','regulator ya dirisha');
add('WINDOW LIFTER','玻璃升降架','lifti ya dirisha');
add('POWER WINDOW MOTOR','玻璃升降电机','mota ya power window');
add('POWER WINDOW SWITCH','玻璃升降开关','switchi ya power window');
add('POWER WINDOW RELAY','玻璃升降继电器','relay ya power window');
add('WINDSHIELD','挡风玻璃','windshield');
add('WINDSHIELD GLASS','前挡风玻璃','kioo cha windshield');
add('WINDSHIELD MOLDING','挡风玻璃饰条','moulding ya windshield');
add('WINDSHIELD SEAL','挡风玻璃密封条','seal ya windshield');
add('REAR WINDSHIELD','后挡风玻璃','windshield ya nyuma');
add('SUNROOF','天窗','sunroof');
add('MOONROOF','天窗','moonroof');
add('SUNROOF GLASS','天窗玻璃','kioo cha sunroof');
add('SUNROOF MOTOR','天窗电机','mota ya sunroof');
add('SUNROOF SEAL','天窗密封条','seal ya sunroof');
add('SUN VISOR','遮阳板','sun visor');
add('MIRROR','后视镜','kioo');
add('SIDE MIRROR','侧后视镜','kioo cha pembeni');
add('DOOR MIRROR','车门后视镜','kioo cha mlango');
add('REAR VIEW MIRROR','后视镜','kioo cha nyuma');
add('ROOM MIRROR','室内后视镜','kioo cha ndani');
add('MIRROR GLASS','后视镜片','kioo cha mirror');
add('MIRROR MOTOR','后视镜电机','mota ya kioo');
add('MIRROR COVER','后视镜壳','kifuniko cha kioo');
add('MIRROR SWITCH','后视镜开关','switchi ya kioo');
add('BUMPER','保险杠','bumper');
add('FRONT BUMPER','前保险杠','bumper ya mbele');
add('REAR BUMPER','后保险杠','bumper ya nyuma');
add('BUMPER COVER','保险杠外皮','kifuniko cha bumper');
add('BUMPER BRACKET','保险杠支架','bracket ya bumper');
add('BUMPER CLIP','保险杠卡扣','clip ya bumper');
add('BUMPER PAD','保险杠缓冲块','padi ya bumper');
add('BUMPER REINFORCEMENT','保险杠加强件','reinforcement ya bumper');
add('BUMPER MOUNT','保险杠固定座','mount ya bumper');
add('GRILLE','中网','grille');
add('FRONT GRILLE','前中网','grille ya mbele');
add('RADIATOR GRILLE','水箱中网','grille ya redieta');
add('GRILLE CHROME','镀铬中网','grille chrome');
add('FENDER TRIM','翼子板饰条','trim ya fender');
add('SIDE PROTECTOR','侧护板','protector ya pembeni');
add('MOULDING','饰条','moulding');
add('DOOR MOULDING','门饰条','moulding ya mlango');
add('SIDE MOULDING','侧饰条','moulding ya pembeni');
add('WINDOW MOULDING','窗饰条','moulding ya dirisha');
add('ROOF','车顶','paa');
add('ROOF RACK','行李架','roof rack');
add('ROOF RAIL','行李架导轨','reli ya paa');
add('ROOF LINING','车顶内衬','mjengo wa paa');
add('HEADLINING','车顶棚','headlining');
add('ANTENNA','天线','antenna');
add('ANTENNA MAST','天线杆','mlingoti ya antenna');
add('ANTENNA BASE','天线底座','msingi wa antenna');
add('SHARK FIN ANTENNA','鲨鱼鳍天线','antenna ya shark fin');
add('SPOILER','尾翼','spoiler');
add('REAR SPOILER','后尾翼','spoiler ya nyuma');
add('LIP SPOILER','唇式尾翼','spoiler ya lip');
add('FRONT LIP','前唇','lip ya mbele');
add('SIDE SKIRT','侧裙','side skirt');
add('REAR DIFFUSER','后扩散器','diffuser ya nyuma');
add('FENDER FLARE','轮眉','flare ya fender');
add('MUD FLAP','挡泥板','mud flap');
add('MUD GUARD','挡泥板','guard ya tope');
add('SIDE STEP','侧踏板','side step');
add('RUNNING BOARD','脚踏板','running board');
add('TOW HITCH COVER','拖车钩盖','kifuniko cha tow hitch');
add('WHEEL ARCH','轮拱','wheel arch');

// ═══════════════════════════════════════════════════════════
// INTERIOR — 内饰 — NDANI
// ═══════════════════════════════════════════════════════════
add('INTERIOR','内饰','ndani');
add('DASHBOARD','仪表台','dashibodi');
add('INSTRUMENT PANEL','仪表板','paneli ya instrument');
add('INSTRUMENT CLUSTER','仪表盘','cluster ya instrument');
add('SPEEDOMETER','车速表','speedometer');
add('TACHOMETER','转速表','tachometer');
add('FUEL GAUGE','油表','geji ya mafuta');
add('TEMPERATURE GAUGE','水温表','geji ya joto');
add('ODOMETER','里程表','odometer');
add('TRIP METER','里程小计','mita ya safari');
add('CENTER CONSOLE','中央扶手箱','console ya kati');
add('GLOVE BOX','手套箱','glove box');
add('GLOVE COMPARTMENT','手套箱','glove compartment');
add('ARMREST','扶手','armrest');
add('CUP HOLDER','杯架','kishikizi cha kikombe');
add('SEAT','座椅','kiti');
add('FRONT SEAT','前座椅','kiti cha mbele');
add('REAR SEAT','后座椅','kiti cha nyuma');
add('DRIVER SEAT','驾驶座','kiti cha dereva');
add('PASSENGER SEAT','副驾驶座','kiti cha abiria');
add('BENCH SEAT','长条座椅','kiti cha benchi');
add('BUCKET SEAT','桶形座椅','kiti cha ndoo');
add('POWER SEAT','电动座椅','kiti cha umeme');
add('HEATED SEAT','加热座椅','kiti chenye joto');
add('SEAT COVER','座套','kifuniko cha kiti');
add('SEAT BELT','安全带','mkanda wa usalama');
add('SEAT BELT BUCKLE','安全带卡扣','buckle ya mkanda');
add('SEAT BELT RETRACTOR','安全带卷收器','retractor ya mkanda');
add('SEAT BELT PRETENSIONER','安全带预紧器','pretensioner');
add('SEAT FRAME','座椅骨架','fremu ya kiti');
add('SEAT RAIL','座椅滑轨','reli ya kiti');
add('SEAT MOTOR','座椅电机','mota ya kiti');
add('SEAT SWITCH','座椅开关','switchi ya kiti');
add('SEAT HEATER','座椅加热器','heater ya kiti');
add('HEADREST','头枕','headrest');
add('CARPET','地毯','zulia');
add('FLOOR MAT','脚垫','kifuniko cha sakafu');
add('RUBBER FLOOR MAT','橡胶脚垫','kifuniko cha sakafu cha mpira');
add('CARGO MAT','后备箱垫','kifuniko cha buti');
add('PEDAL','踏板','pedali');
add('BRAKE PEDAL','刹车踏板','pedali ya breki');
add('ACCELERATOR PEDAL','油门踏板','pedali ya gesi');
add('CLUTCH PEDAL','离合器踏板','pedali ya clutch');
add('PEDAL COVER','踏板套','kifuniko cha pedali');
add('STEERING WHEEL COVER','方向盘套','kifuniko cha steering');
add('SHIFT KNOB COVER','排档套','kifuniko cha shift knob');
add('STEERING WHEEL LEATHER','真皮方向盘','steering ya ngozi');
add('GEAR SHIFT BOOT','排档防尘套','boot ya shift');
add('CIGARETTE LIGHTER','点烟器','kivuta sigara');
add('ASH TRAY','烟灰缸','kishikilia majivu');
add('USB SOCKET','USB插座','socket ya USB');
add('POWER OUTLET','电源插座','kutolea umeme');
add('CIGAR LIGHTER SOCKET','点烟器插座','socket ya kivuta sigara');

// ═══════════════════════════════════════════════════════════
// FLUIDS / CHEMICALS / CONSUMABLES — 油液/化学品/耗材
// ═══════════════════════════════════════════════════════════
add('PETROL','汽油','petroli');
add('DIESEL','柴油','dizeli');
add('PREMIUM PETROL','高级汽油','petroli bora');
add('REGULAR PETROL','普通汽油','petroli ya kawaida');
add('KEROSENE','煤油','mafuta ya taa');
add('WATER','水','maji');
add('DRINKING WATER','饮用水','maji ya kunywa');
add('DISTILLED WATER','蒸馏水','maji yaliyochemshwa');
add('BATTERY WATER','电瓶水','maji ya betri');
add('DEMINERALIZED WATER','去离子水','maji safi');
add('WINDSHIELD WASHER FLUID','玻璃水','maji ya kusafisha windshield');
add('WASHER FLUID','玻璃水','maji ya washer');
add('BRAKE CLEANER','刹车清洗剂','dawa ya kusafisha breki');
add('CARB CLEANER','化油器清洗剂','dawa ya kusafisha carb');
add('THROTTLE CLEANER','节气门清洗剂','dawa ya kusafisha throttle');
add('INTAKE CLEANER','进气道清洗剂','dawa ya kusafisha intake');
add('FUEL INJECTOR CLEANER','喷油嘴清洗剂','dawa ya kusafisha injector');
add('ENGINE CLEANER','发动机清洗剂','dawa ya kusafisha injini');
add('ENGINE DEGREASER','发动机去油剂','dawa ya kuondoa grisi');
add('PARTS CLEANER','零件清洗剂','dawa ya kusafisha vipuri');
add('CARBURETOR CLEANER','化油器清洗剂','dawa ya carburetor');
add('BRAKE FLUID','刹车油','mafuta ya breki');
add('CLUTCH FLUID','离合器油','mafuta ya clutch');
add('GEAR OIL','齿轮油','mafuta ya giya');
add('HYDRAULIC OIL','液压油','mafuta ya hydraulic');
add('HYDRAULIC FLUID','液压油','mafuta ya hydraulic');
add('POWER STEERING FLUID','方向机油','mafuta ya usukani');
add('ATF','自动变速箱油','ATF');
add('CVT FLUID','无级变速箱油','mafuta ya CVT');
add('DIFFERENTIAL OIL','差速器油','mafuta ya difu');
add('TRANSFER CASE OIL','分动箱油','mafuta ya transfer case');
add('LIMITED SLIP ADDITIVE','限滑差速器添加剂','kiongezi cha LSD');
add('OIL STABILIZER','机油稳定剂','stabilizer ya mafuta');
add('ENGINE FLUSH','发动机清洗液','dawa ya kusafisha injini');
add('OIL FLUSH','机油清洗剂','dawa ya kusafisha mafuta');
add('FUEL SYSTEM CLEANER','燃油系统清洗剂','dawa ya kusafisha mfumo wa mafuta');
add('INJECTOR CLEANER','喷油嘴清洗剂','dawa ya injector');
add('DIESEL INJECTOR CLEANER','柴油喷油嘴清洗剂','dawa ya injector ya dizeli');
add('CATALYTIC CLEANER','三元催化清洗剂','dawa ya catalytic');
add('DPF CLEANER','DPF清洗剂','dawa ya DPF');
add('EGR CLEANER','EGR清洗剂','dawa ya EGR');
add('OCTANE BOOSTER','辛烷值提升剂','kiboresha octane');
add('CETANE BOOSTER','十六烷值提升剂','kiboresha cetane');
add('FUEL STABILIZER','燃油稳定剂','stabilizer ya mafuta');
add('WATER REMOVER','燃油除水剂','dawa ya kuondoa maji');
add('ANTIFREEZE','防冻液','antifreeze');
add('COOLANT','冷却液','coolant');
add('COOLANT ADDITIVE','冷却液添加剂','kiongezi cha coolant');
add('RADIATOR STOP LEAK','水箱堵漏剂','dawa ya kuzuia kuvuja redieta');
add('HEAD GASKET REPAIR','缸垫修复剂','dawa ya kurekebisha gasket');
add('ENGINE STOP LEAK','发动机堵漏剂','dawa ya kuzuia kuvuja injini');
add('OIL STOP LEAK','机油堵漏剂','dawa ya kuzuia mafuta kuvuja');
add('POWER STEERING STOP LEAK','方向机堵漏剂','dawa ya kuzuia kuvuja usukani');
add('TRANSMISSION STOP LEAK','变速箱堵漏剂','dawa ya kuzuia kuvuja gearbox');
add('WD-40','除锈润滑剂','WD-40');
add('PENETRATING OIL','渗透润滑剂','mafuta ya kupenya');
add('LUBRICANT','润滑剂','lubricant');
add('GREASE','黄油','grisi');
add('WHITE GREASE','白黄油','grisi nyeupe');
add('LITHIUM GREASE','锂基黄油','grisi ya lithium');
add('SILICONE GREASE','硅脂','grisi ya silicone');
add('COPPER GREASE','铜基黄油','grisi ya shaba');
add('MOLY GREASE','二硫化钼黄油','grisi ya moly');
add('WHEEL BEARING GREASE','轮毂轴承黄油','grisi ya bearing');
add('CV JOINT GREASE','球笼黄油','grisi ya CV');
add('BRAKE GREASE','刹车润滑脂','grisi ya breki');
add('DIELECTRIC GREASE','绝缘硅脂','grisi ya dielectric');
add('ANTI-SEIZE','防卡剂','anti-seize');
add('THREAD LOCKER','螺纹锁固胶','gundi ya nyuzi');
add('LOCTITE','螺纹胶','loctite');
add('GASKET MAKER','密封胶','gundi ya gasketi');
add('SILICONE','硅胶','silicone');
add('RTV SILICONE','RTV硅胶','RTV silicone');
add('ARALDITE','环氧树脂胶','araldite');
add('EPOXY GLUE','环氧胶','gundi ya epoxy');
add('SUPER GLUE','强力胶','gundi kali');
add('INSTANT GLUE','瞬间胶','gundi ya papo');
add('GLUE','胶水','gundi');
add('CONTACT ADHESIVE','万能胶','adhesive ya contact');
add('SILICONE SEALANT','硅胶密封胶','sealant ya silicone');
add('WINDOW SEALANT','玻璃胶','sealant ya dirisha');
add('BODY SEALANT','车身密封胶','sealant ya mwili');
add('UNDERBODY COATING','底盘装甲','coating ya chini');
add('RUBBERIZED UNDERCOATING','底盘防锈胶','undercoating ya mpira');
add('RUST CONVERTER','铁锈转换剂','kigeuza kutu');
add('RUST REMOVER','除锈剂','dawa ya kuondoa kutu');
add('PAINT','油漆','rangi');
add('SPRAY PAINT','喷漆','rangi ya kupuliza');
add('TOUCH UP PAINT','补漆笔','rangi ya kugusa');
add('CLEAR COAT','清漆','clear coat');
add('PRIMER','底漆','primer');
add('PAINT THINNER','稀释剂','thinner');
add('BODY FILLER','原子灰','filler ya mwili');
add('PUTTY','腻子','putty');
add('SAND PAPER','砂纸','sand paper');
add('WET SAND PAPER','水砂纸','sand paper ya maji');
add('MASKING TAPE','美纹纸胶带','tepu ya masking');
add('POLISH','抛光剂','dawa ya kung\'arisha');
add('WAX','车蜡','wax');
add('COMPOUND','研磨剂','compound');
add('CUTTING COMPOUND','粗蜡','compound ya kukata');
add('POLISHING COMPOUND','抛光蜡','compound ya kung\'arisha');
add('CAR SHAMPOO','洗车液','shampoo ya gari');
add('CAR WAX','车蜡','wax ya gari');
add('TIRE SHINE','轮胎蜡','dawa ya kung\'arisha tairi');
add('INTERIOR CLEANER','内饰清洗剂','dawa ya kusafisha ndani');
add('UPHOLSTERY CLEANER','座椅清洗剂','dawa ya kusafisha viti');
add('GLASS CLEANER','玻璃清洗剂','dawa ya kusafisha vioo');
add('CHROME POLISH','镀铬抛光剂','dawa ya kung\'arisha chrome');
add('METAL POLISH','金属抛光剂','dawa ya kung\'arisha chuma');
add('SOAP','肥皂','sabuni');
add('HAND CLEANER','洗手液','sabuni ya mikono');
add('HAND SOAP','洗手液','sabuni ya mikono');
add('TISSUE','纸巾','tissue');
add('PAPER TOWEL','纸巾','taulo ya karatasi');
add('RAG','抹布','kitambaa');
add('COTTON WASTE','废棉纱','pamba taka');
add('WORKSHOP TOWEL','车间毛巾','taulo ya workshop');
add('BROOM','扫把','fagio');
add('MOP','拖把','mop');
add('DUST BIN','垃圾桶','pipala takataka');
add('TRASH BAG','垃圾袋','mifuko ya takataka');
add('TOILET CLEANER','洁厕液','dawa ya kusafisha choo');
add('DISINFECTANT','消毒水','dawa ya kuua viini');
add('AIR FRESHENER','空气清新剂','dawa ya harufu');
add('INSECT SPRAY','杀虫剂','dawa ya wadudu');
add('BATTERY TERMINAL CLEANER','电瓶桩头清洗剂','dawa ya kusafisha terminal');
add('BATTERY TERMINAL PROTECTOR','电瓶桩头保护剂','dawa ya kulinda terminal');
add('ELECTRICAL CONTACT CLEANER','电器接点清洗剂','dawa ya kusafisha contact');
add('MASS AIR FLOW CLEANER','空气流量计清洗剂','dawa ya MAF');

// ═══════════════════════════════════════════════════════════
// SERVICE / LABOR — 人工/服务 — SERVICE / KAZI
// ═══════════════════════════════════════════════════════════
add('SERVICE','保养','service');
add('FULL SERVICE','大保养','service kamili');
add('MINOR SERVICE','小保养','service ndogo');
add('MAJOR SERVICE','大保养','service kubwa');
add('OIL SERVICE','换机油保养','service ya mafuta');
add('OIL CHANGE','换机油','kubadilisha mafuta');
add('OIL FILTER CHANGE','换机油滤清器','kubadilisha chujio la mafuta');
add('AIR FILTER CHANGE','换空气滤清器','kubadilisha chujio la hewa');
add('FUEL FILTER CHANGE','换燃油滤清器','kubadilisha chujio la mafuta');
add('CABIN FILTER CHANGE','换空调滤清器','kubadilisha chujio la cabin');
add('SPARK PLUG CHANGE','换火花塞','kubadilisha spark plug');
add('TIRE CHANGE','换轮胎','kubadilisha tairi');
add('TIRE REPAIR','补胎','kutengeneza tairi');
add('BRAKE PAD CHANGE','换刹车片','kubadilisha padi za breki');
add('BRAKE DISC CHANGE','换刹车盘','kubadilisha disc za breki');
add('TIMING BELT CHANGE','换正时皮带','kubadilisha mkanda wa timing');
add('TIMING CHAIN CHANGE','换正时链条','kubadilisha cheni ya timing');
add('CLUTCH CHANGE','换离合器','kubadilisha clutch');
add('WATER PUMP CHANGE','换水泵','kubadilisha pampu ya maji');
add('RADIATOR CHANGE','换水箱','kubadilisha redieta');
add('SHOCK CHANGE','换减震器','kubadilisha shock');
add('SPRING CHANGE','换弹簧','kubadilisha springi');
add('BATTERY CHANGE','换电瓶','kubadilisha betri');
add('ALTERNATOR CHANGE','换发电机','kubadilisha alterneta');
add('STARTER CHANGE','换启动机','kubadilisha starter');
add('BELT CHANGE','换皮带','kubadilisha mkanda');
add('HOSE CHANGE','换软管','kubadilisha hose');
add('FILTER CHANGE','换滤清器','kubadilisha chujio');
add('FLUID CHANGE','换油液','kubadilisha mafuta');
add('FUNDI','人工费','mshahara wa fundi');
add('MECHANIC','修理工','fundi');
add('LABOR','人工','kazi');
add('LABOUR','人工费','gharama ya kazi');
add('OVERHAUL','大修','overhaul');
add('ENGINE OVERHAUL','发动机大修','overhaul ya injini');
add('GEARBOX OVERHAUL','变速箱大修','overhaul ya gearbox');
add('DIFFERENTIAL OVERHAUL','差速器大修','overhaul ya difu');
add('REBUILD','翻新','kujenga upya');
add('REPAIR','维修','kutengeneza');
add('REPLACEMENT','更换','kubadilisha');
add('INSTALLATION','安装','kuweka');
add('REMOVAL','拆卸','kutoa');
add('DIAGNOSIS','诊断','utambuzi');
add('INSPECTION','检查','ukaguzi');
add('CHECK','检查','kukagua');
add('ADJUSTMENT','调整','kurekebisha');
add('TUNING','调校','kutengeneza');
add('TUNE-UP','调校','tune-up');
add('CLEANING','清洗','kusafisha');
add('WASHING','洗涤','kuosha');
add('CAR WASH','洗车','kuosha gari');
add('ENGINE WASH','洗发动机','kuosha injini');
add('CHASSIS WASH','洗底盘','kuosha chassis');
add('POLISHING','抛光','kung\'arisha');
add('PAINTING','喷漆','kupaka rangi');
add('WELDING','焊接','kuchomea');
add('EXHAUST WELDING','排气管焊接','kuchomea exhaust');
add('BODY REPAIR','车身维修','kutengeneza mwili');
add('PANEL BEATING','钣金','kugonga paneli');
add('DENT REMOVAL','凹陷修复','kuondoa mfuo');
add('PAINTLESS DENT REPAIR','无痕凹陷修复','kutengeneza mfuo bila rangi');
add('SCRATCH REPAIR','划痕修复','kutengeneza mkwaruzo');
add('BUMPER REPAIR','保险杠修复','kutengeneza bumper');
add('WINDSHIELD REPAIR','挡风玻璃修复','kutengeneza windshield');
add('HEADLIGHT RESTORATION','大灯翻新','kurejesha taa');
add('AC SERVICE','空调保养','service ya AC');
add('AC RECHARGE','空调加氟','kujaza gesi AC');
add('AC REPAIR','空调维修','kutengeneza AC');
add('WHEEL ALIGNMENT','四轮定位','alignment ya magurudumu');
add('WHEEL BALANCING','轮胎动平衡','kusawazisha magurudumu');
add('TIRE ROTATION','轮胎换位','kuzungusha matairi');
add('BRAKE BLEEDING','刹车排气','kutoa hewa breki');
add('COOLANT FLUSH','更换冷却液','kubadilisha coolant');
add('TRANSMISSION FLUSH','变速箱换油','kubadilisha mafuta ya gearbox');
add('BRAKE FLUSH','刹车油更换','kubadilisha mafuta ya breki');
add('POWER STEERING FLUSH','方向机油更换','kubadilisha mafuta ya usukani');
add('FUEL SYSTEM CLEANING','燃油系统清洗','kusafisha mfumo wa mafuta');
add('INTAKE CLEANING','进气道清洗','kusafisha intake');
add('THROTTLE CLEANING','节气门清洗','kusafisha throttle');
add('INJECTOR CLEANING','喷油嘴清洗','kusafisha injector');
add('EGR CLEANING','EGR清洗','kusafisha EGR');
add('DPF CLEANING','DPF清洗','kusafisha DPF');
add('ENGINE SCANNING','发动机检测','kuchanganua injini');
add('OBD DIAGNOSIS','OBD诊断','utambuzi wa OBD');
add('COMPUTER DIAGNOSIS','电脑诊断','utambuzi wa kompyuta');
add('ELECTRICAL DIAGNOSIS','电路诊断','utambuzi wa umeme');
add('TRANSPORT','运输费','usafiri');
add('DELIVERY','送货费','usafirishaji');
add('TOWING','拖车费','kuvuta gari');
add('RECOVERY','救援费','uokoaji');
add('DRIVER','司机费','dereva');
add('BODA FARE','摩托车费','nauli ya boda');
add('MOTORCYCLE PETROL','摩托车汽油','petroli ya pikipiki');
add('OVERTIME','加班费','malipo ya ziada');
add('BONUS','奖金','bonus');
add('TIP','小费','tip');
add('OSHA','安全费','ada ya osha');
add('PERMIT','许可证费','ada ya kibali');
add('PARKING','停车费','ada ya maegesho');
add('TOLL','过路费','ada ya ushuru');
add('FUEL','燃油费','gharama ya mafuta');

// Final output
console.log(Object.keys(dict).length + ' entries generated.');
fs.writeFileSync('parts_master.json', JSON.stringify(dict, null, 2), 'utf-8');
console.log('Written to parts_master.json');
